Repository kubernetes-sigs/kubefed, pull requests merged in 2018-06, with the labels that each got.

#93 Add a user guide
  README.md
  docs/development.md
  docs/userguide.md
  example/sample1/federatedconfigmap-override.yaml
  example/sample1/federatedconfigmap-placement.yaml
  example/sample1/federatedconfigmap-template.yaml
  example/sample1/federateddeployment-override.yaml
  example/sample1/federateddeployment-placement.yaml
  example/sample1/federateddeployment-template.yaml
  example/sample1/federatednamespace-placement.yaml
  example/sample1/federatednamespace-template.yaml
  example/sample1/federatedsecret-override.yaml
  example/sample1/federatedsecret-placement.yaml
  example/sample1/federatedsecret-template.yaml
  scripts/delete-federation.sh
  scripts/deploy-federation.sh
  scripts/download-binaries.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#105 Add feature gates
  cmd/controller-manager/main.go
  pkg/features/features.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#109 Make ReplicaSchedulingPreference controller generic to support both FederatedDeployment and FederatedReplicaSet
  pkg/apis/federatedscheduling/v1alpha1/replicaschedulingpreference_types.go
  pkg/apis/federatedscheduling/v1alpha1/zz_generated.conversion.go
  pkg/apis/federatedscheduling/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/federatedscheduling/v1alpha1/zz_generated.defaults.go
  pkg/apis/federatedscheduling/zz_generated.api.register.go
  pkg/apis/federatedscheduling/zz_generated.deepcopy.go
  pkg/apis/federatedscheduling/zz_generated.defaults.go
  pkg/apis/federation/zz_generated.api.register.go
  pkg/client/clientset_generated/clientset/typed/federatedscheduling/v1alpha1/doc.go
  pkg/client/clientset_generated/clientset/typed/federatedscheduling/v1alpha1/fake/doc.go
  pkg/client/clientset_generated/clientset/typed/federatedscheduling/v1alpha1/fake/fake_federatedscheduling_client.go
  pkg/client/clientset_generated/clientset/typed/federatedscheduling/v1alpha1/fake/fake_replicaschedulingpreference.go
  pkg/client/clientset_generated/clientset/typed/federatedscheduling/v1alpha1/federatedscheduling_client.go
  pkg/client/clientset_generated/clientset/typed/federatedscheduling/v1alpha1/generated_expansion.go
  pkg/client/clientset_generated/clientset/typed/federatedscheduling/v1alpha1/replicaschedulingpreference.go
  pkg/client/clientset_generated/internalclientset/typed/federatedscheduling/internalversion/doc.go
  pkg/client/clientset_generated/internalclientset/typed/federatedscheduling/internalversion/fake/doc.go
  pkg/client/clientset_generated/internalclientset/typed/federatedscheduling/internalversion/fake/fake_federatedscheduling_client.go
  pkg/client/clientset_generated/internalclientset/typed/federatedscheduling/internalversion/fake/fake_replicaschedulingpreference.go
  pkg/client/clientset_generated/internalclientset/typed/federatedscheduling/internalversion/federatedscheduling_client.go
  pkg/client/clientset_generated/internalclientset/typed/federatedscheduling/internalversion/generated_expansion.go
  pkg/client/clientset_generated/internalclientset/typed/federatedscheduling/internalversion/replicaschedulingpreference.go
  pkg/client/informers_generated/externalversions/federatedscheduling/interface.go
  pkg/client/informers_generated/externalversions/federatedscheduling/v1alpha1/interface.go
  pkg/client/informers_generated/externalversions/federatedscheduling/v1alpha1/replicaschedulingpreference.go
  pkg/client/informers_generated/internalversion/federatedscheduling/interface.go
  pkg/client/informers_generated/internalversion/federatedscheduling/internalversion/interface.go
  pkg/client/informers_generated/internalversion/federatedscheduling/internalversion/replicaschedulingpreference.go
  pkg/client/listers_generated/federatedscheduling/internalversion/expansion_generated.go
  pkg/client/listers_generated/federatedscheduling/internalversion/replicaschedulingpreference.go
  pkg/client/listers_generated/federatedscheduling/v1alpha1/expansion_generated.go
  pkg/client/listers_generated/federatedscheduling/v1alpha1/replicaschedulingpreference.go
  pkg/controller/replicaschedulingpreference/controller.go
  pkg/controller/replicaschedulingpreference/scheduler/deployment.go
  pkg/controller/replicaschedulingpreference/scheduler/plugin.go
  pkg/controller/replicaschedulingpreference/scheduler/scheduler.go
  pkg/controller/sync/controller.go
  pkg/controller/util/constants.go
  pkg/controller/util/podanalyzer/pod_helper.go
  pkg/controller/util/podanalyzer/pod_helper_test.go
  pkg/openapi/openapi_generated.go
  test/integration/replicaschedulingpreference_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#122 Add travis badge to README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#123 Fix broken password var in imagebuild.sh
  scripts/imagebuild.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#124 Add pmorie to approvers
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#125 Specify repo name for image build
  scripts/imagebuild.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS
