Repository kubernetes-sigs/kubefed, pull requests merged in 2018-10, with the labels that each got.

#295 Enabled delete federation can delete hack/install.yaml
  docs/userguide.md
  scripts/delete-federation.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#299 Avoid starting a namespace sync controller for namespaced federation
  pkg/controller/federatedtypeconfig/controller.go
  scripts/deploy-federation.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#284 Target in-memory controllers in e2e at the test namespace
  test/e2e/framework/framework.go
  test/e2e/framework/managed.go
  test/e2e/framework/test_context.go
  test/e2e/framework/unmanaged.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#296 Refactor all controllers to use the same async worker code
  pkg/controller/federatedtypeconfig/controller.go
  pkg/controller/ingressdns/controller.go
  pkg/controller/schedulingpreference/controller.go
  pkg/controller/servicedns/controller.go
  pkg/controller/sync/controller.go
  pkg/controller/util/worker.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#307 Fix compilation issue
  pkg/controller/federatedtypeconfig/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#308 Misc fixes for font comments on previous PRs
  pkg/controller/util/overrides.go
  pkg/controller/util/worker.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#301 Expand on foundational concepts in README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#290 Fine-grained deploy for cluster scoped federation controller.
  scripts/delete-federation.sh
  scripts/deploy-federation.sh
  scripts/generate-install-yaml.sh
  scripts/generate-namespaced-install-yaml.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#315 Use Makefile to build binaries with version info
  Makefile
  scripts/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#312 Add godoc for PropagatedVersion
  pkg/apis/core/v1alpha1/propagatedversion_types.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#322 Fix crudtester version retrieval
  test/common/crudtester.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#321 Randomize order of test execution in ci
  scripts/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#287 Updated user guide for namespaced federation.
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#288 User documentation for replica scheduling preferences
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#276 Factor type-specific version manager code into adapter
  pkg/controller/sync/controller.go
  pkg/controller/sync/version.go
  pkg/controller/sync/version/adapter.go
  pkg/controller/sync/version/manager.go
  pkg/controller/sync/version/namespaced.go
  test/e2e/version.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#328 Fix version manager iteration
  pkg/controller/sync/version/adapter.go
  pkg/controller/sync/version/manager.go
  pkg/controller/sync/version/namespaced.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#309 Support defaulting to namespace placement for namespace-scoped federation
  pkg/controller/sync/controller.go
  pkg/controller/sync/placement/namespace.go
  pkg/controller/sync/placement/namespaced.go
  pkg/controller/sync/placement/plugin.go
  pkg/controller/sync/placement/resource.go
  test/common/crudtester.go
  test/e2e/crud.go
  test/e2e/placement.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#320 Example to federate a CRD in the target cluster
  docs/federating_crds.md
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#327 Use ownerReference to ensure PropagatedVersion removal
  pkg/controller/sync/controller.go
  pkg/controller/sync/version/adapter.go
  pkg/controller/sync/version/manager.go
  pkg/controller/sync/version/namespaced.go
  test/common/crudtester.go
  test/e2e/version.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#337 Add ci check for 'kubebuilder generate' making no changes
  scripts/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#316 Adds GKE Deployment Documentation
  docs/environments/gke.md
  docs/environments/minikube.md
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#341 Add examples of CRD propagation, fix crd propagation guide
  docs/federating_crds.md
  example/crd/bar_crd.yaml
  example/crd/federatedBar.yaml
  example/crd/federatedbar_crd.yaml
  example/crd/federatedbar_test.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#339 Reduce flakes in e2e testing
  scripts/pre-commit.sh
  test/e2e/version.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#335 Cleanup crd test to simplify validation of cluster-scoped propagation
  test/common/crudtester.go
  test/e2e/crd.go
  test/e2e/crud.go
  test/e2e/framework/framework.go
  test/e2e/framework/managed.go
  test/e2e/framework/unmanaged.go
  test/integration/framework/federation.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#344 Add CI check that hack/install-latest.yaml is up-to-date
  hack/install-latest.yaml
  scripts/generate-install-yaml.sh
  scripts/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#311 Improve godoc for MultiClusterServiceDNSRecord and DNSEndpoint
  pkg/apis/multiclusterdns/v1alpha1/dnsendpoint_types.go
  pkg/apis/multiclusterdns/v1alpha1/servicednsrecord_types.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#334 Add ClusterPropagatedVersion
  hack/install-latest.yaml
  pkg/apis/core/v1alpha1/clusterpropagatedversion_types.go
  pkg/apis/core/v1alpha1/clusterpropagatedversion_types_test.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1alpha1/zz_generated.kubebuilder.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/clusterpropagatedversion.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/core_client.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_clusterpropagatedversion.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_core_client.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/generated_expansion.go
  pkg/client/informers/externalversions/core/v1alpha1/clusterpropagatedversion.go
  pkg/client/informers/externalversions/core/v1alpha1/interface.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/core/v1alpha1/clusterpropagatedversion.go
  pkg/client/listers/core/v1alpha1/expansion_generated.go
  pkg/inject/zz_generated.kubebuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#351 Removed the List from all exampes.
  example/sample1/federatedconfigmap-override.yaml
  example/sample1/federatedconfigmap-placement.yaml
  example/sample1/federatedconfigmap-template.yaml
  example/sample1/federateddeployment-override.yaml
  example/sample1/federateddeployment-placement.yaml
  example/sample1/federateddeployment-template.yaml
  example/sample1/federatedjob-placement.yaml
  example/sample1/federatednamespace-placement.yaml
  example/sample1/federatedsecret-override.yaml
  example/sample1/federatedsecret-placement.yaml
  example/sample1/federatedsecret-template.yaml
  example/sample1/federatedserviceaccount-placement.yaml
  example/sample1/federatedserviceaccount-template.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#346 Document release procedure.
  docs/releasing.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#352 Updated user guide by adding steps for helm chart install.
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#332 Support propagation of cluster-scoped resources
  pkg/controller/federatedtypeconfig/controller.go
  pkg/controller/sync/controller.go
  pkg/controller/sync/version/adapter.go
  pkg/controller/sync/version/cluster.go
  pkg/controller/sync/version/manager.go
  pkg/controller/sync/version/namespaced.go
  test/common/crudtester.go
  test/common/testobjects.go
  test/e2e/crd.go
  test/e2e/version.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#359 Remove duplicate default values in controller-manager help text
  cmd/controller-manager/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#357 Support multiple field overrides
  config/federatedtypes/configmap.yaml
  config/federatedtypes/deployment.yaml
  config/federatedtypes/job.yaml
  config/federatedtypes/replicaset.yaml
  config/federatedtypes/secret.yaml
  hack/install-latest.yaml
  pkg/apis/core/typeconfig/interface.go
  pkg/apis/core/v1alpha1/federatedtypeconfig_types.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1alpha1/zz_generated.kubebuilder.go
  pkg/controller/sync/controller.go
  pkg/controller/util/overrides.go
  scripts/download-binaries.sh
  test/common/crudtester.go
  test/common/fixtures/deployment-override.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L
