Repository kubernetes-sigs/kubefed, pull requests merged in 2018-04, with the labels that each got.

#37 To add FederatedJob
  docs/examples/federatedjob/federatedjob.yaml
  pkg/apis/federation/v1alpha1/federatedjob_types.go
  pkg/apis/federation/v1alpha1/federatedjob_types_test.go
  pkg/apis/federation/v1alpha1/federatedjoboverride_types.go
  pkg/apis/federation/v1alpha1/federatedjoboverride_types_test.go
  pkg/apis/federation/v1alpha1/federatedjobplacement_types.go
  pkg/apis/federation/v1alpha1/federatedjobplacement_types_test.go
  pkg/apis/federation/v1alpha1/zz_generated.api.register.go
  pkg/apis/federation/v1alpha1/zz_generated.conversion.go
  pkg/apis/federation/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/federation/zz_generated.api.register.go
  pkg/apis/federation/zz_generated.deepcopy.go
  pkg/client/clientset_generated/clientset/typed/federation/v1alpha1/fake/fake_federatedjob.go
  pkg/client/clientset_generated/clientset/typed/federation/v1alpha1/fake/fake_federatedjoboverride.go
  pkg/client/clientset_generated/clientset/typed/federation/v1alpha1/fake/fake_federatedjobplacement.go
  pkg/client/clientset_generated/clientset/typed/federation/v1alpha1/fake/fake_federation_client.go
  pkg/client/clientset_generated/clientset/typed/federation/v1alpha1/federatedjob.go
  pkg/client/clientset_generated/clientset/typed/federation/v1alpha1/federatedjoboverride.go
  pkg/client/clientset_generated/clientset/typed/federation/v1alpha1/federatedjobplacement.go
  pkg/client/clientset_generated/clientset/typed/federation/v1alpha1/federation_client.go
  pkg/client/clientset_generated/clientset/typed/federation/v1alpha1/generated_expansion.go
  pkg/client/clientset_generated/internalclientset/typed/federation/internalversion/fake/fake_federatedjob.go
  pkg/client/clientset_generated/internalclientset/typed/federation/internalversion/fake/fake_federatedjoboverride.go
  pkg/client/clientset_generated/internalclientset/typed/federation/internalversion/fake/fake_federatedjobplacement.go
  pkg/client/clientset_generated/internalclientset/typed/federation/internalversion/fake/fake_federation_client.go
  pkg/client/clientset_generated/internalclientset/typed/federation/internalversion/federatedjob.go
  pkg/client/clientset_generated/internalclientset/typed/federation/internalversion/federatedjoboverride.go
  pkg/client/clientset_generated/internalclientset/typed/federation/internalversion/federatedjobplacement.go
  pkg/client/clientset_generated/internalclientset/typed/federation/internalversion/federation_client.go
  pkg/client/clientset_generated/internalclientset/typed/federation/internalversion/generated_expansion.go
  pkg/client/informers_generated/externalversions/federation/v1alpha1/federatedjob.go
  pkg/client/informers_generated/externalversions/federation/v1alpha1/federatedjoboverride.go
  pkg/client/informers_generated/externalversions/federation/v1alpha1/federatedjobplacement.go
  pkg/client/informers_generated/externalversions/federation/v1alpha1/interface.go
  pkg/client/informers_generated/externalversions/generic.go
  pkg/client/informers_generated/internalversion/federation/internalversion/federatedjob.go
  pkg/client/informers_generated/internalversion/federation/internalversion/federatedjoboverride.go
  pkg/client/informers_generated/internalversion/federation/internalversion/federatedjobplacement.go
  pkg/client/informers_generated/internalversion/federation/internalversion/interface.go
  pkg/client/informers_generated/internalversion/generic.go
  pkg/client/listers_generated/federation/internalversion/expansion_generated.go
  pkg/client/listers_generated/federation/internalversion/federatedjob.go
  pkg/client/listers_generated/federation/internalversion/federatedjoboverride.go
  pkg/client/listers_generated/federation/internalversion/federatedjobplacement.go
  pkg/client/listers_generated/federation/v1alpha1/expansion_generated.go
  pkg/client/listers_generated/federation/v1alpha1/federatedjob.go
  pkg/client/listers_generated/federation/v1alpha1/federatedjoboverride.go
  pkg/client/listers_generated/federation/v1alpha1/federatedjobplacement.go
  pkg/controller/federatedjob/controller.go
  pkg/controller/federatedjob/controller_test.go
  pkg/controller/federatedjob/federatedjob_suite_test.go
  pkg/controller/federatedjob/zz_generated.api.register.go
  pkg/controller/sharedinformers/zz_generated.api.register.go
  pkg/controller/zz_generated.api.register.go
  pkg/federatedtypes/job.go
  pkg/openapi/openapi_generated.go
  sample/federatedjob.yaml
Labels: cncf-cla: yes, size/XXL

#58 Enable auth for cloud providers
  cmd/kubefnord/kubefnord.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#63 Add override struct tag for federated deployment, replicaset, and job
  pkg/apis/federation/v1alpha1/federateddeploymentoverride_types.go
  pkg/apis/federation/v1alpha1/federatedjoboverride_types.go
  pkg/apis/federation/v1alpha1/federatedreplicasetoverride_types.go
  pkg/apis/federation/zz_generated.api.register.go
  pkg/openapi/openapi_generated.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#36 Document E2E tests
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#65 Workaround ns version handling issue
  pkg/controller/sync/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
