Repository kubernetes-sigs/kubefed, pull requests merged in 2018-07, with the labels that each got.

#126 Use correct link for adding a new API type in development.md
  docs/development.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#134 Change scope of FederatedCluster to be Namespaced
  pkg/apis/core/v1alpha1/federatedcluster_types.go
  pkg/apis/core/v1alpha1/zz_generated.kubebuilder.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/core_client.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_core_client.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_federatedcluster.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/federatedcluster.go
  pkg/client/informers/externalversions/core/v1alpha1/federatedcluster.go
  pkg/client/informers/externalversions/core/v1alpha1/interface.go
  pkg/client/listers/core/v1alpha1/expansion_generated.go
  pkg/client/listers/core/v1alpha1/federatedcluster.go
  pkg/controller/federatedcluster/controller.go
  pkg/controller/util/federated_informer.go
  pkg/kubefnord/join.go
  test/e2e/framework/unmanaged.go
  test/e2e/servicedns.go
  test/integration/framework/federation.go
  test/integration/replicaschedulingpreference_test.go
  test/integration/servicedns_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#139 Do not need namespace for clusterrole and clusterrolebindings.
  pkg/kubefnord/join.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#140 Add util.FederatedSystemNamespace where it is missing
  pkg/apis/core/v1alpha1/federatedcluster_types_test.go
  test/integration/framework/framework_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#141 Updated integration link for development guide.
  docs/development.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#146 Need to specify sa namespace when create clusterrolebindings.
  pkg/kubefnord/join.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#136 Update image build to incorporate kubebuilder merge
  hack/install-latest.yaml
  images/federation-v2/Dockerfile
  scripts/delete-federation.sh
  scripts/deploy-federation-latest.sh
  scripts/deploy-federation.sh
  scripts/imagebuild.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#156 Fix canary image build
  images/federation-v2/Dockerfile
  scripts/imagebuild.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#149 Rename kubefnord to kubefed and implement simple kubefed version
  cmd/kubefed2/kubefed2.go
  docs/userguide.md
  pkg/kubefed2/join.go
  pkg/kubefed2/kubefed2.go
  pkg/kubefed2/options/options.go
  pkg/kubefed2/util/util.go
  pkg/kubefed2/version.go
  scripts/deploy-federation.sh
  scripts/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#147 Add more debug log in join.
  pkg/kubefed2/join.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#158 Update travis.yml to include support for tagging
  scripts/imagebuild.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#168 Fix tagging format for image build
  scripts/imagebuild.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#170 Echo travis branch/tag ENV VARS
  scripts/imagebuild.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#172 Fix issues with kubefed2 join
  pkg/kubefed2/join.go
  pkg/kubefed2/kubefed2.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#174 Add v to front of version tag and cleanup
  scripts/imagebuild.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#160 Automate fixing of install yaml
  .gitignore
  hack/install-latest.yaml
  scripts/deploy-federation.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#167 Implement versioning with git tag and sha info
  Makefile
  cmd/controller-manager/main.go
  pkg/kubefed2/version.go
  pkg/version/base.go
  pkg/version/version.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#176 Remove Dockerfile.controller to prevent confusion
  Dockerfile.controller
  docs/development.md
  scripts/deploy-federation-latest.sh
  scripts/deploy-federation.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#178 Updated KubeFnord to KubeFed2.
  pkg/kubefed2/kubefed2.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#171 Introduce retry loop for federatedcluster status update
  test/integration/servicedns_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#180 Rename `Host` to `HostClusterContext` for `join`.
  pkg/kubefed2/join.go
  pkg/kubefed2/options/options.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#166 Flush log immediately for controller manager.
  cmd/controller-manager/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#179 Fix docker tag for latest
  scripts/imagebuild.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#181 Correct the path for docker file.
  docs/development.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#164 Fix join to use passed-in federation namespace instead of a constant
  pkg/kubefed2/join.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#137 Implemented unjoin.
  pkg/kubefed2/kubefed2.go
  pkg/kubefed2/unjoin.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#185 Adding Contribution guidelines
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#190 Update latest config to use latest image
  hack/install-latest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
