Repository kubernetes-sigs/kubefed, pull requests merged in 2018-05, with the labels that each got.

#57 Add deployment script
  .gitignore
  scripts/delete-federation.sh
  scripts/deploy-federation.sh
  scripts/download-binaries.sh
  scripts/pre-commit.sh
  scripts/util.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#62 Refine usage of the dynamic client
  pkg/controller/sync/controller.go
  pkg/controller/sync/placement/plugin.go
  pkg/controller/sync/placement/resource.go
  pkg/controller/util/genericinformer.go
  pkg/controller/util/resourceclient.go
  pkg/controller/util/resourceinformer.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#68 Migrate crudtester to use the dynamic client
  pkg/controller/sync/controller.go
  pkg/controller/sync/placement/resource.go
  pkg/controller/util/placement.go
  pkg/controller/util/resourceclient.go
  pkg/federatedtypes/adapter.go
  pkg/federatedtypes/apiresource.go
  pkg/federatedtypes/configmap.go
  pkg/federatedtypes/deployment.go
  pkg/federatedtypes/job.go
  pkg/federatedtypes/namespace.go
  pkg/federatedtypes/registry.go
  pkg/federatedtypes/replicaset.go
  pkg/federatedtypes/secret.go
  pkg/federatedtypes/service.go
  pkg/federatedtypes/testobjregistry.go
  test/common/crudtester.go
  test/common/fixtures/configmap-override.yaml
  test/common/fixtures/configmap-template.yaml
  test/common/fixtures/deployment-override.yaml
  test/common/fixtures/deployment-template.yaml
  test/common/fixtures/job-override.yaml
  test/common/fixtures/job-template.yaml
  test/common/fixtures/namespace-template.yaml
  test/common/fixtures/placement.yaml
  test/common/fixtures/replicaset-override.yaml
  test/common/fixtures/replicaset-template.yaml
  test/common/fixtures/secret-override.yaml
  test/common/fixtures/secret-template.yaml
  test/common/fixtures/service-template.yaml
  test/common/testobjects.go
  test/e2e/crud.go
  test/e2e/framework/framework.go
  test/e2e/framework/managed.go
  test/e2e/framework/unmanaged.go
  test/integration/crud_test.go
  test/integration/framework/federation.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#69 Migrate sync controller to use the dynamic client
  cmd/controller-manager/main.go
  pkg/apis/federation/v1alpha1/federateddeploymentoverride_types.go
  pkg/apis/federation/v1alpha1/federatedjoboverride_types.go
  pkg/apis/federation/v1alpha1/federatedreplicasetoverride_types.go
  pkg/apis/federation/v1alpha1/federatedsecretoverride_types.go
  pkg/controller/sync/controller.go
  pkg/controller/sync/placement/namespace.go
  pkg/controller/util/federated_informer.go
  pkg/controller/util/federated_updater.go
  pkg/federatedtypes/configmap.go
  pkg/federatedtypes/deployment.go
  pkg/federatedtypes/job.go
  pkg/federatedtypes/registry.go
  pkg/federatedtypes/replicaset.go
  pkg/federatedtypes/secret.go
  test/e2e/crud.go
  test/e2e/framework/framework.go
  test/e2e/framework/managed.go
  test/e2e/framework/unmanaged.go
  test/integration/crud_test.go
  test/integration/framework/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#70 Delete unused type adapters
  pkg/controller/sync/controller.go
  pkg/controller/util/deletionhelper/deletion_helper.go
  pkg/federatedtypes/adapter.go
  pkg/federatedtypes/configmap.go
  pkg/federatedtypes/deployment.go
  pkg/federatedtypes/job.go
  pkg/federatedtypes/namespace.go
  pkg/federatedtypes/registry.go
  pkg/federatedtypes/replicaset.go
  pkg/federatedtypes/secret.go
  pkg/federatedtypes/service.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#72 Remove pkg/federatedtypes
  pkg/controller/sync/controller.go
  pkg/controller/util/constants.go
  pkg/controller/util/deletionhelper/deletion_helper.go
  pkg/controller/util/qualifiedname.go
  pkg/federatedtypes/apiresource.go
  pkg/federatedtypes/configmap.go
  pkg/federatedtypes/deployment.go
  pkg/federatedtypes/job.go
  pkg/federatedtypes/namespace.go
  pkg/federatedtypes/registry.go
  pkg/federatedtypes/replicaset.go
  pkg/federatedtypes/secret.go
  pkg/federatedtypes/service.go
  test/common/crudtester.go
  test/e2e/crud.go
  test/integration/crud_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#79 Fix a flake issue in integration test
  test/common/crudtester.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#99 Update owners file to add folks from Huawei
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS
