Repository kubernetes-sigs/kubefed, pull requests merged in 2018-09, with the labels that each got.

#243 Log federation-v2 version in controller-manager
  cmd/controller-manager/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#222 kubefed: clean up role and binding creation
  pkg/kubefed2/join.go
  pkg/kubefed2/unjoin.go
  pkg/kubefed2/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#224 Add godoc for FederatedCluster
  pkg/apis/core/v1alpha1/federatedcluster_types.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#200 Added back github.com/kubernetes/repo-infra to Gopkg.toml
  Gopkg.toml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#225 Rename --cluster-namespace to --registry-namespace
  pkg/kubefed2/join.go
  pkg/kubefed2/options/options.go
  test/e2e/framework/test_context.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#249 Add script to generate install yaml
  scripts/deploy-federation.sh
  scripts/generate-install-yaml.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#250 Upgrade Kubebuilder to v1.0.3.
  docs/development.md
  docs/userguide.md
  scripts/download-binaries.sh
  scripts/generate-install-yaml.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#253 Improve e2e reliability
  pkg/controller/util/placement.go
  scripts/download-e2e-binaries.sh
  scripts/pre-commit.sh
  test/common/crudtester.go
  test/common/fixtures/deployment-override.yaml
  test/common/fixtures/deployment-template.yaml
  test/common/fixtures/job-template.yaml
  test/common/fixtures/replicaset-override.yaml
  test/common/fixtures/replicaset-template.yaml
  test/e2e/framework/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#260 s/clustername/clusterName/ everywhere
  docs/userguide.md
  example/sample1/federatedconfigmap-override.yaml
  example/sample1/federatedconfigmap-placement.yaml
  example/sample1/federateddeployment-override.yaml
  example/sample1/federateddeployment-placement.yaml
  example/sample1/federatednamespace-placement.yaml
  example/sample1/federatedsecret-override.yaml
  example/sample1/federatedsecret-placement.yaml
  example/sample1/federatedservice-placement.yaml
  pkg/controller/sync/controller.go
  pkg/controller/util/constants.go
  pkg/controller/util/placement.go
  test/common/testobjects.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#244 Fixes for namespace-scoped federatednamespaceplacement
  docs/userguide.md
  example/sample1/federatednamespace-placement.yaml
  pkg/controller/sync/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#234 Adds ServiceAccount Support
  config/federatedtypes/serviceaccount.yaml
  docs/userguide.md
  example/sample1/federatedserviceaccount-placement.yaml
  example/sample1/federatedserviceaccount-template.yaml
  pkg/apis/core/v1alpha1/federatedserviceaccount_types.go
  pkg/apis/core/v1alpha1/federatedserviceaccount_types_test.go
  pkg/apis/core/v1alpha1/federatedserviceaccountplacement_types.go
  pkg/apis/core/v1alpha1/federatedserviceaccountplacement_types_test.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1alpha1/zz_generated.kubebuilder.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/core_client.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_core_client.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_federatedserviceaccount.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_federatedserviceaccountplacement.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/federatedserviceaccount.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/federatedserviceaccountplacement.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/generated_expansion.go
  pkg/client/informers/externalversions/core/v1alpha1/federatedserviceaccount.go
  pkg/client/informers/externalversions/core/v1alpha1/federatedserviceaccountplacement.go
  pkg/client/informers/externalversions/core/v1alpha1/interface.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/core/v1alpha1/expansion_generated.go
  pkg/client/listers/core/v1alpha1/federatedserviceaccount.go
  pkg/client/listers/core/v1alpha1/federatedserviceaccountplacement.go
  pkg/inject/zz_generated.kubebuilder.go
  test/common/fixtures/serviceaccount-template.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#236 Add godoc for FederatedCluster controller
  pkg/controller/federatedcluster/clusterclient.go
  pkg/controller/federatedcluster/controller.go
  pkg/controller/util/cluster_util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#230 Ensure control plane can run with only authz for the federation namespace
  cmd/controller-manager/main.go
  pkg/controller/federatedtypeconfig/controller.go
  pkg/controller/sync/controller.go
  scripts/delete-federation.sh
  scripts/deploy-federation.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#238 MultiCluster Ingress DNS endpoint controller
  cmd/controller-manager/main.go
  pkg/controller/dnsendpoint/common.go
  pkg/controller/dnsendpoint/common_test.go
  pkg/controller/dnsendpoint/controller.go
  pkg/controller/dnsendpoint/ingress.go
  pkg/controller/dnsendpoint/ingress_test.go
  pkg/controller/dnsendpoint/service.go
  pkg/controller/dnsendpoint/service_test.go
  pkg/controller/servicednsendpoint/servicednsendpoint_controller.go
  test/common/dns.go
  test/e2e/ingressdns.go
  test/e2e/servicedns.go
  test/integration/framework/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#263 Added example for federatedJob.
  docs/userguide.md
  example/sample1/federateddeployment-template.yaml
  example/sample1/federatedjob-override.yaml
  example/sample1/federatedjob-placement.yaml
  example/sample1/federatedjob-template.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#254 Cleanup e2e readiness
  pkg/controller/util/federated_informer.go
  test/e2e/e2e.go
  test/e2e/framework/unmanaged.go
  test/integration/framework/cluster.go
  test/integration/framework/federation.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#240 Update docs on using master canary or latest stable version image
  docs/development.md
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#264 Add doc for deployment of namespaced federation
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#269 Lock pendingVersionUpdates
  pkg/controller/sync/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#223 Add godoc for FederatedTypeConfig
  pkg/apis/core/v1alpha1/federatedtypeconfig_types.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#274 Update concepts diagram in README
  README.md
  docs/images/concepts.png
  docs/images/propagation.png
Labels: approved, cncf-cla: yes, lgtm, size/XS

#268 Added ReplicaSchedulingPreference example.
  example/scheduling/federateddeployment-rsp.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#277 Add quay badge to README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#273 Factor propagated version handling out of the sync controller
  pkg/apis/core/common/util.go
  pkg/controller/sync/controller.go
  pkg/controller/sync/version.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#245 Helm chart for federation v2.
  charts/federation-v2/Chart.yaml
  charts/federation-v2/LICENSE
  charts/federation-v2/README.md
  charts/federation-v2/charts/clusterregistry/Chart.yaml
  charts/federation-v2/charts/clusterregistry/templates/_helpers.tpl
  charts/federation-v2/charts/clusterregistry/templates/crds.yaml
  charts/federation-v2/charts/federatedtypes/Chart.yaml
  charts/federation-v2/charts/federatedtypes/templates/_helpers.tpl
  charts/federation-v2/charts/federatedtypes/templates/configmap.yaml
  charts/federation-v2/charts/federatedtypes/templates/deployment.yaml
  charts/federation-v2/charts/federatedtypes/templates/ingress.yaml
  charts/federation-v2/charts/federatedtypes/templates/job.yaml
  charts/federation-v2/charts/federatedtypes/templates/namespace.yaml
  charts/federation-v2/charts/federatedtypes/templates/replicaset.yaml
  charts/federation-v2/charts/federatedtypes/templates/secret.yaml
  charts/federation-v2/charts/federatedtypes/templates/service.yaml
  charts/federation-v2/charts/federatedtypes/templates/serviceaccount.yaml
  charts/federation-v2/requirements.yaml
  charts/federation-v2/templates/_helpers.tpl
  charts/federation-v2/templates/clusterrole.yaml
  charts/federation-v2/templates/clusterrolebindings.yaml
  charts/federation-v2/templates/crds.yaml
  charts/federation-v2/templates/service.yaml
  charts/federation-v2/templates/statefulset.yaml
  charts/federation-v2/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#281 Changes to support releasing v0.0.2-rc.1
  docs/userguide.md
  hack/install-latest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#266 Add check of application of overrides to the crudtester
  pkg/controller/sync/controller.go
  pkg/controller/util/overrides.go
  test/common/crudtester.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#285 Fix controller manager to only accept args from command line
  cmd/controller-manager/main.go
  scripts/generate-namespaced-install-yaml.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#289 Enable -ginkgo.trace for ci testing
  scripts/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#282 Added "--name federation" for crd generation script.
  scripts/generate-install-crds-yaml.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#270 Add optional ObservedGeneration field to DNSEndpointStatus
  pkg/apis/core/v1alpha1/zz_generated.kubebuilder.go
  pkg/apis/multiclusterdns/v1alpha1/dnsendpoint_types.go
  pkg/apis/multiclusterdns/v1alpha1/zz_generated.kubebuilder.go
  pkg/apis/scheduling/v1alpha1/zz_generated.kubebuilder.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_federatedcluster.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_federatedconfigmap.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_federatedconfigmapoverride.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_federatedconfigmapplacement.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_federateddeployment.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_federateddeploymentoverride.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_federateddeploymentplacement.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_federatedingress.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_federatedingressplacement.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_federatedjob.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_federatedjoboverride.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_federatedjobplacement.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_federatednamespaceplacement.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_federatedreplicaset.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_federatedreplicasetoverride.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_federatedreplicasetplacement.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_federatedsecret.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_federatedsecretoverride.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_federatedsecretplacement.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_federatedservice.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_federatedserviceaccount.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_federatedserviceaccountplacement.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_federatedserviceplacement.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_federatedtypeconfig.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_propagatedversion.go
  pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_dnsendpoint.go
  pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusteringressdnsrecord.go
  pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusterservicednsrecord.go
  pkg/client/clientset/versioned/typed/scheduling/v1alpha1/fake/fake_replicaschedulingpreference.go
  pkg/client/informers/externalversions/factory.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#293 Use `clusterNames` for federated serviceaccount placement.
  example/sample1/federatedserviceaccount-placement.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#286 Use namespace sync controller in the dns tests
  test/common/dns.go
  test/common/typeconfig.go
  test/e2e/crud.go
  test/e2e/framework/framework.go
  test/e2e/ingressdns.go
  test/e2e/servicedns.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#292 Fixed a log issue for join.
  pkg/kubefed2/join.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#142 Adding myself as reviewer.
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#278 Added one-liner note for a command to project its importance
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
