Repository kubernetes-sigs/kubefed, pull requests merged in 2018-08, with the labels that each got.

#192 Use unjoin when remove cluster from federation.
  scripts/delete-federation.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#193 Updated userguide to highlight the usage of automatic deploy and delete.
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#184 Enable CI e2e job against single minikube cluster
  .travis.yml
  scripts/deploy-federation.sh
  scripts/download-binaries.sh
  scripts/download-e2e-binaries.sh
  scripts/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#194 Refactor scheduling
  cmd/controller-manager/main.go
  pkg/controller/schedulingpreference/controller.go
  pkg/schedulingtypes/adapters/deployment.go
  pkg/schedulingtypes/adapters/interface.go
  pkg/schedulingtypes/adapters/replicaset.go
  pkg/schedulingtypes/interface.go
  pkg/schedulingtypes/plugin.go
  pkg/schedulingtypes/replicascheduler.go
  pkg/schedulingtypes/resources.go
  pkg/schedulingtypes/typeregistry.go
  test/integration/framework/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#196 Ignore controller manager.
  .gitignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#186 Serve DNS endpoints from CRD
  cmd/controller-manager/main.go
  pkg/apis/multiclusterdns/v1alpha1/dnsendpoint_types.go
  pkg/apis/multiclusterdns/v1alpha1/dnsendpoint_types_test.go
  pkg/apis/multiclusterdns/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/multiclusterdns/v1alpha1/zz_generated.kubebuilder.go
  pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/dnsendpoint.go
  pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_dnsendpoint.go
  pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusterdns_client.go
  pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/multiclusterdns_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/multiclusterdns/v1alpha1/dnsendpoint.go
  pkg/client/informers/externalversions/multiclusterdns/v1alpha1/interface.go
  pkg/client/listers/multiclusterdns/v1alpha1/dnsendpoint.go
  pkg/client/listers/multiclusterdns/v1alpha1/expansion_generated.go
  pkg/controller/servicednsendpoint/servicednsendpoint_controller.go
  pkg/controller/servicednsendpoint/servicednsendpoint_controller_test.go
  pkg/inject/zz_generated.kubebuilder.go
  test/e2e/servicedns.go
  test/integration/framework/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#199 Increase mem resources for fed controller, add federated service example, other misc. changes
  docs/development.md
  docs/userguide.md
  example/sample1/federateddeployment-template.yaml
  example/sample1/federatedservice-placement.yaml
  example/sample1/federatedservice-template.yaml
  hack/install-latest.yaml
  pkg/controller/federatedcluster/controller.go
  scripts/deploy-federation.sh
  test/e2e/e2e_test.go
  vendor/k8s.io/cluster-registry/cluster-registry-crd.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#205 Bump e2e poll timeout to account for unmanaged fixture on travis
  test/e2e/framework/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#191 Update kubebuilder binary version to 1.0.0
  docs/userguide.md
  scripts/download-binaries.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#198 Allow the federation system namespace to be configured in testing
  cmd/controller-manager/main.go
  pkg/apis/core/v1alpha1/federatedcluster_types_test.go
  pkg/controller/federatedcluster/clusterclient.go
  pkg/controller/federatedcluster/controller.go
  pkg/controller/federatedtypeconfig/controller.go
  pkg/controller/schedulingpreference/controller.go
  pkg/controller/servicedns/controller.go
  pkg/controller/sync/controller.go
  pkg/controller/util/cluster_util.go
  pkg/controller/util/federated_informer.go
  pkg/kubefed2/options/options.go
  pkg/schedulingtypes/interface.go
  pkg/schedulingtypes/plugin.go
  pkg/schedulingtypes/replicascheduler.go
  test/e2e/framework/framework.go
  test/e2e/framework/managed.go
  test/e2e/framework/test_context.go
  test/e2e/framework/unmanaged.go
  test/e2e/servicedns.go
  test/integration/crud_test.go
  test/integration/framework/controller.go
  test/integration/framework/federation.go
  test/integration/framework/framework_test.go
  test/integration/integration_test.go
  test/integration/replicaschedulingpreference_test.go
  test/integration/servicedns_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#206 Simple Ingress propogation to member clusters
  config/federatedtypes/ingress.yaml
  pkg/apis/core/v1alpha1/federatedingress_types.go
  pkg/apis/core/v1alpha1/federatedingress_types_test.go
  pkg/apis/core/v1alpha1/federatedingressplacement_types.go
  pkg/apis/core/v1alpha1/federatedingressplacement_types_test.go
  pkg/apis/core/v1alpha1/federatedtypeconfig_types.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1alpha1/zz_generated.kubebuilder.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/core_client.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_core_client.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_federatedingress.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_federatedingressplacement.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/federatedingress.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/federatedingressplacement.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/generated_expansion.go
  pkg/client/informers/externalversions/core/v1alpha1/federatedingress.go
  pkg/client/informers/externalversions/core/v1alpha1/federatedingressplacement.go
  pkg/client/informers/externalversions/core/v1alpha1/interface.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/core/v1alpha1/expansion_generated.go
  pkg/client/listers/core/v1alpha1/federatedingress.go
  pkg/client/listers/core/v1alpha1/federatedingressplacement.go
  pkg/inject/zz_generated.kubebuilder.go
  test/common/fixtures/ingress-template.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#207 Make DNS record TTL configurable by user
  pkg/apis/multiclusterdns/v1alpha1/dnsendpoint_types.go
  pkg/apis/multiclusterdns/v1alpha1/multiclusterservicednsrecord_types.go
  pkg/apis/multiclusterdns/v1alpha1/zz_generated.kubebuilder.go
  pkg/controller/servicednsendpoint/servicednsendpoint_controller.go
  pkg/controller/servicednsendpoint/servicednsendpoint_controller_test.go
  test/e2e/servicedns.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#213 Enable kubefed2 config of federation and cluster namespaces
  pkg/kubefed2/join.go
  pkg/kubefed2/options/options.go
  pkg/kubefed2/unjoin.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#211 Allow the cluster registry namespace to vary in testing
  cmd/controller-manager/main.go
  pkg/controller/federatedcluster/clusterclient.go
  pkg/controller/federatedcluster/controller.go
  pkg/controller/federatedtypeconfig/controller.go
  pkg/controller/schedulingpreference/controller.go
  pkg/controller/servicedns/controller.go
  pkg/controller/sync/controller.go
  pkg/controller/util/cluster_util.go
  pkg/controller/util/federated_informer.go
  pkg/schedulingtypes/interface.go
  pkg/schedulingtypes/plugin.go
  pkg/schedulingtypes/replicascheduler.go
  test/e2e/framework/managed.go
  test/e2e/framework/test_context.go
  test/e2e/framework/unmanaged.go
  test/integration/crud_test.go
  test/integration/framework/controller.go
  test/integration/framework/federation.go
  test/integration/integration_test.go
  test/integration/replicaschedulingpreference_test.go
  test/integration/servicedns_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#209 Update FederatedTypeConfig to be namespace-scoped
  docs/userguide.md
  hack/install-latest.yaml
  pkg/apis/core/v1alpha1/federatedtypeconfig_types.go
  pkg/apis/core/v1alpha1/federatedtypeconfig_types_test.go
  pkg/apis/core/v1alpha1/zz_generated.kubebuilder.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/core_client.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_core_client.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_federatedtypeconfig.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/federatedtypeconfig.go
  pkg/client/informers/externalversions/core/v1alpha1/federatedtypeconfig.go
  pkg/client/informers/externalversions/core/v1alpha1/interface.go
  pkg/client/listers/core/v1alpha1/expansion_generated.go
  pkg/client/listers/core/v1alpha1/federatedtypeconfig.go
  pkg/controller/federatedtypeconfig/controller.go
  scripts/deploy-federation.sh
  test/common/crudtester.go
  test/e2e/crud.go
  test/e2e/framework/unmanaged.go
  test/integration/framework/federation.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#221 Extends Pluralization Support
  pkg/apis/core/v1alpha1/federatedtypeconfig_types.go
  pkg/apis/core/v1alpha1/federatedtypeconfig_types_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#210 Update FederatedNamespacePlacement to be namespace-scoped
  pkg/apis/core/v1alpha1/federatednamespaceplacement_types.go
  pkg/apis/core/v1alpha1/federatedtypeconfig_types.go
  pkg/apis/core/v1alpha1/zz_generated.kubebuilder.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/core_client.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_core_client.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_federatednamespaceplacement.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/federatednamespaceplacement.go
  pkg/client/informers/externalversions/core/v1alpha1/federatednamespaceplacement.go
  pkg/client/informers/externalversions/core/v1alpha1/interface.go
  pkg/client/listers/core/v1alpha1/expansion_generated.go
  pkg/client/listers/core/v1alpha1/federatednamespaceplacement.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#215 Enable kubefed to join a cluster for only the federation namespace
  pkg/kubefed2/join.go
  pkg/kubefed2/options/options.go
  pkg/kubefed2/unjoin.go
  pkg/kubefed2/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#212 Allow the target namespace to vary in testing
  cmd/controller-manager/main.go
  pkg/controller/federatedtypeconfig/controller.go
  pkg/controller/schedulingpreference/controller.go
  pkg/controller/servicedns/controller.go
  pkg/controller/sync/controller.go
  pkg/controller/util/federated_informer.go
  pkg/schedulingtypes/interface.go
  pkg/schedulingtypes/plugin.go
  pkg/schedulingtypes/replicascheduler.go
  test/e2e/framework/managed.go
  test/e2e/framework/test_context.go
  test/e2e/framework/unmanaged.go
  test/integration/crud_test.go
  test/integration/framework/controller.go
  test/integration/integration_test.go
  test/integration/replicaschedulingpreference_test.go
  test/integration/servicedns_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#229 Bump e2e timeout to avoid deployment e2e timeout
  test/e2e/framework/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#228 Fixes Delete Bug in Delete Script
  scripts/delete-federation.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#217 Updated install-latest.yaml.
  hack/install-latest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#231 Enable e2e test timeout to be configured
  scripts/pre-commit.sh
  test/e2e/crud.go
  test/e2e/framework/framework.go
  test/e2e/framework/test_context.go
  test/e2e/framework/unmanaged.go
  test/e2e/framework/util.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#233 Remove /config from .gitignore
  .gitignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#218 Add IngressDNSRecord type for FederatedIngress
  cmd/controller-manager/main.go
  pkg/apis/multiclusterdns/v1alpha1/multiclusteringressdnsrecord_types.go
  pkg/apis/multiclusterdns/v1alpha1/multiclusteringressdnsrecord_types_test.go
  pkg/apis/multiclusterdns/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/multiclusterdns/v1alpha1/zz_generated.kubebuilder.go
  pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusterdns_client.go
  pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusteringressdnsrecord.go
  pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/multiclusterdns_client.go
  pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/multiclusteringressdnsrecord.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/multiclusterdns/v1alpha1/interface.go
  pkg/client/informers/externalversions/multiclusterdns/v1alpha1/multiclusteringressdnsrecord.go
  pkg/client/listers/multiclusterdns/v1alpha1/expansion_generated.go
  pkg/client/listers/multiclusterdns/v1alpha1/multiclusteringressdnsrecord.go
  pkg/controller/ingressdns/controller.go
  pkg/features/features.go
  pkg/inject/zz_generated.kubebuilder.go
  test/common/dns.go
  test/e2e/framework/framework.go
  test/e2e/framework/managed.go
  test/e2e/framework/unmanaged.go
  test/e2e/ingressdns.go
  test/e2e/servicedns.go
  test/integration/framework/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#235 Reduce federated informer error messages
  pkg/controller/util/federated_informer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#239 Update install-latest.yaml to work with latest image
  hack/install-latest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
