Repository kubernetes-sigs/kubefed, pull requests merged in 2018-12, with the labels that each got.

#462 IngressDNSRecord should be in test-namespace in ingressdns-with-externaldns.md
  docs/ingressdns-with-externaldns.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#476 Changed apiVerison from core.federation.k8s.io/v1alpha1 to primitives.federation.k8s.io/v1alpha1
  example/sample1/federatedconfigmap-override.yaml
  example/sample1/federatedconfigmap-placement.yaml
  example/sample1/federatedconfigmap-template.yaml
  example/sample1/federateddeployment-override.yaml
  example/sample1/federateddeployment-placement.yaml
  example/sample1/federateddeployment-template.yaml
  example/sample1/federatedingress-placement.yaml
  example/sample1/federatedingress-template.yaml
  example/sample1/federatedjob-override.yaml
  example/sample1/federatedjob-placement.yaml
  example/sample1/federatedjob-template.yaml
  example/sample1/federatednamespace-placement.yaml
  example/sample1/federatedsecret-override.yaml
  example/sample1/federatedsecret-placement.yaml
  example/sample1/federatedsecret-template.yaml
  example/sample1/federatedservice-placement.yaml
  example/sample1/federatedservice-template.yaml
  example/sample1/federatedserviceaccount-placement.yaml
  example/sample1/federatedserviceaccount-template.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#432 Added script to sync up CRD resources in helm chart.
  charts/federation-v2/charts/controllermanager/templates/crds.yaml
  scripts/pre-commit.sh
  scripts/sync-up-helm-chart.sh
Labels: approved, cncf-cla: yes, lgtm, size/XL

#478 Use prettier to format the md file.
  charts/federation-v2/README.md
  docs/concepts.md
  docs/development.md
  docs/environments/gke.md
  docs/federating_crds.md
  docs/ingressdns-with-externaldns.md
  docs/releasing.md
  docs/servicedns-with-externaldns.md
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#436 Always load the namespace type config from the api
  pkg/controller/federatedtypeconfig/controller.go
  pkg/controller/sync/controller.go
  test/e2e/framework/framework.go
  test/e2e/framework/managed.go
  test/e2e/framework/managed/controller.go
  test/e2e/framework/unmanaged.go
  test/e2e/placement.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#486 Fix unit test issues and run unit tests in ci
  Makefile
  charts/federation-v2/charts/controllermanager/templates/crds.yaml
  hack/install-latest.yaml
  pkg/apis/core/v1alpha1/federatedcluster_types_test.go
  pkg/apis/core/v1alpha1/federatedservicestatus_types_test.go
  pkg/apis/core/v1alpha1/federatedtypeconfig_types.go
  pkg/apis/core/v1alpha1/federatedtypeconfig_types_test.go
  pkg/apis/multiclusterdns/v1alpha1/domain_types.go
  pkg/apis/multiclusterdns/v1alpha1/domain_types_test.go
  pkg/apis/multiclusterdns/v1alpha1/zz_generated.kubebuilder.go
  pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusteringressdnsrecord.go
  pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusterservicednsrecord.go
  pkg/controller/federatedtypeconfig/controller.go
  scripts/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#467 Sets type config template pluralname
  pkg/kubefed2/federate/enable.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#454 Implement generic overrides
  charts/federation-v2/charts/controllermanager/templates/crds.yaml
  config/federatedirectives/configmaps.yaml
  config/federatedirectives/deployments.apps.yaml
  config/federatedirectives/jobs.batch.yaml
  config/federatedirectives/replicasets.apps.yaml
  config/federatedirectives/secrets.yaml
  hack/install-latest.yaml
  pkg/apis/core/typeconfig/interface.go
  pkg/apis/core/v1alpha1/federatedtypeconfig_types.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1alpha1/zz_generated.kubebuilder.go
  pkg/controller/sync/controller.go
  pkg/controller/util/constants.go
  pkg/controller/util/overrides.go
  pkg/kubefed2/federate/directive.go
  pkg/kubefed2/federate/enable.go
  pkg/kubefed2/federate/schema.go
  pkg/kubefed2/federate/validation.go
  pkg/schedulingtypes/plugin.go
  test/common/crudtester.go
  test/common/fixtures/configmaps.yaml
  test/common/fixtures/deployments.apps.yaml
  test/common/fixtures/jobs.batch.yaml
  test/common/fixtures/replicasets.apps.yaml
  test/common/fixtures/secrets.yaml
  test/common/testobjects.go
  test/e2e/crd.go
  test/e2e/scheduling.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#444 Adds region/zone level custom naming support for ServiceDNSRecords
  charts/federation-v2/charts/controllermanager/templates/crds.yaml
  hack/install-latest.yaml
  pkg/apis/multiclusterdns/v1alpha1/servicednsrecord_types.go
  pkg/apis/multiclusterdns/v1alpha1/zz_generated.kubebuilder.go
  pkg/controller/dnsendpoint/service.go
  pkg/controller/dnsendpoint/service_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#484 Allow placement to be set by label selector
  pkg/controller/sync/controller.go
  pkg/controller/sync/placement/namespace.go
  pkg/controller/sync/placement/namespaced.go
  pkg/controller/sync/placement/plugin.go
  pkg/controller/sync/placement/resource.go
  pkg/controller/sync/placement/resource_test.go
  pkg/controller/util/placement.go
  pkg/kubefed2/federate/validation.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#465 fix flag include problem
  cmd/controller-manager/app/controller-manager.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#485 Sync up federation YAML templates for helm chart
  charts/federation-v2/charts/controllermanager/templates/clusterrole.yaml
  charts/federation-v2/charts/controllermanager/templates/role.yaml
  charts/federation-v2/templates/clusterroles.rbac.authorization.k8s.io.yaml
  charts/federation-v2/templates/configmap.yaml
  charts/federation-v2/templates/configmaps.yaml
  charts/federation-v2/templates/deployment.yaml
  charts/federation-v2/templates/deployments.apps.yaml
  charts/federation-v2/templates/ingress.yaml
  charts/federation-v2/templates/ingresses.extensions.yaml
  charts/federation-v2/templates/job.yaml
  charts/federation-v2/templates/jobs.batch.yaml
  charts/federation-v2/templates/namespace.yaml
  charts/federation-v2/templates/namespaces.yaml
  charts/federation-v2/templates/replicaset.yaml
  charts/federation-v2/templates/replicasets.apps.yaml
  charts/federation-v2/templates/secret.yaml
  charts/federation-v2/templates/secrets.yaml
  charts/federation-v2/templates/service.yaml
  charts/federation-v2/templates/serviceaccount.yaml
  charts/federation-v2/templates/serviceaccounts.yaml
  charts/federation-v2/templates/services.yaml
  scripts/pre-commit.sh
  scripts/sync-up-helm-chart.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#498 Disable helm chart check until the crds can be updated reliably
  scripts/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#468 Updates clusterrole rules to include all NonResourceURLs
  pkg/kubefed2/join.go
  pkg/kubefed2/unjoin.go
  pkg/kubefed2/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#493 Use `yaml` for yaml files in user guide.
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#494 comment the suggested docker version in the user guide
  docs/development.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#504 Update helm crds to support clusterSelector
  charts/federation-v2/templates/clusterroles.rbac.authorization.k8s.io.yaml
  charts/federation-v2/templates/configmaps.yaml
  charts/federation-v2/templates/deployments.apps.yaml
  charts/federation-v2/templates/ingresses.extensions.yaml
  charts/federation-v2/templates/jobs.batch.yaml
  charts/federation-v2/templates/namespaces.yaml
  charts/federation-v2/templates/replicasets.apps.yaml
  charts/federation-v2/templates/secrets.yaml
  charts/federation-v2/templates/serviceaccounts.yaml
  charts/federation-v2/templates/services.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#502 Update example overrides to be generic
  example/sample1/federatedconfigmap-override.yaml
  example/sample1/federateddeployment-override.yaml
  example/sample1/federatedjob-override.yaml
  example/sample1/federatedsecret-override.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#499 Added a PR template.
  .github/PULL_REQUEST_TEMP
Labels: approved, cncf-cla: yes, lgtm, size/S

#503 Update docs to reflect `kubefed federate`
  docs/development.md
  docs/federating_crds.md
  docs/userguide.md
  example/crd/bar_crd.yaml
  example/crd/federatedBar.yaml
  example/crd/federatedbar_crd.yaml
  example/crd/federatedbar_test.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#470 Fix enabling federation for CustomResourceDefinition
  pkg/kubefed2/federate/schema.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#455 Require the override field in FederatedTypeConfig
  hack/install-latest.yaml
  pkg/apis/core/typeconfig/interface.go
  pkg/apis/core/v1alpha1/federatedtypeconfig_types.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1alpha1/zz_generated.kubebuilder.go
  pkg/controller/sync/controller.go
  pkg/kubefed2/federate/disable.go
  pkg/kubefed2/federate/enable.go
  pkg/schedulingtypes/plugin.go
  test/common/crudtester.go
  test/common/testobjects.go
  test/e2e/scheduling.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#449 Added document for install federation v2 on IBM Cloud Private.
  docs/environments/icp.md
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#521 Fixes for PR503
  docs/userguide.md
  pkg/kubefed2/federate/enable.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#492 Added document for clusterSelector.
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#517 Add apiGroup to the FederatedClusterRoleBinding example
  example/sample1/federatedclusterrolebinding-template.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#528 Fix dev guide reference to integration test fixture
  docs/development.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#529 Log version status update conflicts as warnings rather than errors
  pkg/controller/sync/version/manager.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#522 automate consistent update of primitive crds
  charts/federation-v2/charts/controllermanager/templates/crds.yaml
  charts/federation-v2/templates/deployments.apps.yaml
  charts/federation-v2/templates/jobs.batch.yaml
  charts/federation-v2/templates/namespaces.yaml
  charts/federation-v2/templates/replicasets.apps.yaml
  docs/development.md
  scripts/pre-commit.sh
  scripts/sync-up-helm-chart.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
