Repository kubernetes-sigs/kubefed, pull requests merged in 2018-11, with the labels that each got.

#378 Update kubebuilder to 1.0.4 in userguide.
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#371 Add flags to controller-manager to set cluster availability delays
  cmd/controller-manager/main.go
  pkg/controller/federatedtypeconfig/controller.go
  pkg/controller/ingressdns/controller.go
  pkg/controller/schedulingpreference/controller.go
  pkg/controller/servicedns/controller.go
  pkg/controller/sync/controller.go
  pkg/controller/util/cluster_util.go
  test/integration/framework/controller.go
  test/integration/servicedns_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#369 Fix validation
  docs/federating_crds.md
  example/crd/bar_crd.yaml
  example/crd/federatedbar_crd.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#340 Add 'kubefed2 federate' command
  pkg/apis/core/typeconfig/interface.go
  pkg/apis/core/v1alpha1/federatedtypeconfig_types.go
  pkg/kubefed2/federate/disable.go
  pkg/kubefed2/federate/enable.go
  pkg/kubefed2/federate/federate.go
  pkg/kubefed2/federate/util.go
  pkg/kubefed2/join.go
  pkg/kubefed2/kubefed2.go
  test/common/testobjects.go
  test/e2e/crd.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#338 Adds FederatedClusterRole Examples and Test Fixture
  example/sample1/federatedclusterrole-placement.yaml
  example/sample1/federatedclusterrole-template.yaml
  test/common/fixtures/clusterrole-template.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#385 Fix typos: fuly -> fully
  pkg/controller/util/planner/planner_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#384 Fix typos: syncronises -> synchronises
  pkg/controller/schedulingpreference/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#343 Adds FederatedClusterRoleBinding Examples and Test Fixture
  example/sample1/federatedclusterrolebinding-placement.yaml
  example/sample1/federatedclusterrolebinding-template.yaml
  test/common/fixtures/clusterrolebinding-template.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#363 Added a troubleshooting section for user guide.
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#361 Adding Go-fmt tools and fixing go-fmt errors
  hack/go-tools/verify-gofmt.sh
  hack/update-gofmt.sh
  pkg/controller/sync/controller.go
  scripts/pre-commit.sh
  test/e2e/crud.go
  test/integration/framework/federation.go
  test/integration/servicedns_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#382 Refactor all controllers to accept a common config struct
  cmd/controller-manager/main.go
  pkg/controller/dnsendpoint/ingress.go
  pkg/controller/dnsendpoint/service.go
  pkg/controller/federatedcluster/controller.go
  pkg/controller/federatedtypeconfig/controller.go
  pkg/controller/ingressdns/controller.go
  pkg/controller/schedulingpreference/controller.go
  pkg/controller/servicedns/controller.go
  pkg/controller/sync/controller.go
  pkg/controller/util/controllerconfig.go
  pkg/controller/util/federated_informer.go
  pkg/schedulingtypes/interface.go
  pkg/schedulingtypes/plugin.go
  pkg/schedulingtypes/replicascheduler.go
  test/e2e/framework/managed.go
  test/e2e/framework/unmanaged.go
  test/integration/crud_test.go
  test/integration/framework/controller.go
  test/integration/framework/federation.go
  test/integration/integration_test.go
  test/integration/replicaschedulingpreference_test.go
  test/integration/servicedns_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#380 Add docs/OWNERS
  docs/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/S

#388 update yaml in chart to reflect multiple override format
  charts/federation-v2/templates/configmap.yaml
  charts/federation-v2/templates/deployment.yaml
  charts/federation-v2/templates/job.yaml
  charts/federation-v2/templates/replicaset.yaml
  charts/federation-v2/templates/secret.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#393 Disable gofmt check until it can be made reliable
  scripts/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#398 Update minikube instructions to reflect released version state
  docs/environments/minikube.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#366 Run controllers based on system configuration
  cmd/controller-manager/main.go
  pkg/controller/schedulingmanager/controller.go
  pkg/controller/schedulingpreference/controller.go
  pkg/schedulingtypes/interface.go
  pkg/schedulingtypes/replicascheduler.go
  pkg/schedulingtypes/resources.go
  test/integration/framework/controller.go
  test/integration/replicaschedulingpreference_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#387 Add missing weight to user guide RSP example
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#405 Removes alpha clusters requirement from gke doc
  docs/environments/gke.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#376 Add option to output yaml to 'kubefed federate enable'
  pkg/kubefed2/federate/enable.go
  pkg/kubefed2/federate/util.go
  test/e2e/crd.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#411 Fix typos: triggerred -> triggered
  pkg/controller/schedulingpreference/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#391 Remove test-specific setup from the e2e framework
  test/e2e/crud.go
  test/e2e/framework/framework.go
  test/e2e/framework/managed.go
  test/e2e/framework/test_context.go
  test/e2e/framework/unmanaged.go
  test/e2e/ingressdns.go
  test/e2e/servicedns.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#392 Migrate integration tests to e2e managed
  docs/development.md
  scripts/pre-commit.sh
  test/e2e/framework/framework.go
  test/e2e/framework/managed.go
  test/e2e/framework/managed/cluster.go
  test/e2e/framework/managed/controller.go
  test/e2e/framework/managed/etcd.go
  test/e2e/framework/managed/federation.go
  test/e2e/framework/managed/kubeapi.go
  test/e2e/framework/managed/logger.go
  test/e2e/framework/managed/secureconfig.go
  test/e2e/framework/managed/util.go
  test/e2e/framework/unmanaged.go
  test/e2e/ingressdns.go
  test/e2e/scheduling.go
  test/e2e/servicedns.go
  test/integration/crud_test.go
  test/integration/integration_test.go
  test/integration/servicedns_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#414 Re-enabling the gofmt CI check
  scripts/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#408 Updated helm chart based on latest code.
  charts/federation-v2/charts/controllermanager/templates/crds.yaml
  charts/federation-v2/templates/service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#403 Set observedGeneration in the federatedTypeConfig controller
  hack/install-latest.yaml
  pkg/apis/core/v1alpha1/federatedtypeconfig_types.go
  pkg/apis/core/v1alpha1/zz_generated.kubebuilder.go
  pkg/controller/federatedtypeconfig/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#421 Fixed examples in the sample1 folder
  docs/userguide.md
  example/sample1/federatedclusterrole-placement.yaml
  example/sample1/federatedclusterrole-template.yaml
  example/sample1/federatedclusterrolebinding-placement.yaml
  example/sample1/federatedclusterrolebinding-template.yaml
  example/sample1/federatedconfigmap-override.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#377 Add validation schema to primitives generated by 'federate enable'
  Gopkg.lock
  Gopkg.toml
  pkg/kubefed2/federate/enable.go
  pkg/kubefed2/federate/schema.go
  pkg/kubefed2/federate/util.go
  pkg/kubefed2/federate/validation.go
  test/e2e/crd.go
  vendor/k8s.io/kubectl/LICENSE
  vendor/k8s.io/kubectl/pkg/framework/openapi/doc.go
  vendor/k8s.io/kubectl/pkg/framework/openapi/extensions.go
  vendor/k8s.io/kubectl/pkg/framework/openapi/openapi.go
  vendor/k8s.io/kubectl/pkg/framework/openapi/openapi_getter.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#423 Reorder primitive creation by crudtester to minimize test runtime
  test/common/crudtester.go
  test/common/testobjects.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#419 Update the comment of the function
  pkg/schedulingtypes/replicascheduler.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#397 install.yaml: fix have coherent namespace on tuto
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#416 Based Docker image on alpine linux to fix security issues
  Makefile
  docs/development.md
  images/federation-v2/Dockerfile
  scripts/deploy-federation.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#417 Add informational output to federate subcommands
  pkg/kubefed2/federate/disable.go
  pkg/kubefed2/federate/enable.go
  test/e2e/crd.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#420 Introduce hyperfed command as a wrapper
  .gitignore
  Gopkg.lock
  Makefile
  cmd/controller-manager/app/controller-manager.go
  cmd/controller-manager/app/options/options.go
  cmd/controller-manager/main.go
  cmd/hyperfed/main.go
  cmd/kubefed2/kubefed2.go
  docs/development.md
  images/federation-v2/Dockerfile
  scripts/deploy-federation.sh
  scripts/imagebuild.sh
Labels: approved, cncf-cla: yes, lgtm, size/XL

#399 Migrate ReplicaSchedulingPreferences controller to the dynamic client
  pkg/controller/schedulingmanager/controller.go
  pkg/controller/schedulingpreference/controller.go
  pkg/controller/util/constants.go
  pkg/controller/util/overrides.go
  pkg/controller/util/placement.go
  pkg/schedulingtypes/adapters/deployment.go
  pkg/schedulingtypes/adapters/interface.go
  pkg/schedulingtypes/adapters/replicaset.go
  pkg/schedulingtypes/interface.go
  pkg/schedulingtypes/plugin.go
  pkg/schedulingtypes/replicascheduler.go
  pkg/schedulingtypes/resources.go
  pkg/schedulingtypes/typeregistry.go
  test/common/testobjects.go
  test/e2e/framework/managed/controller.go
  test/e2e/scheduling.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#422 Switch 'federate disable' to using explicit ftc name
  pkg/kubefed2/federate/disable.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#428 Enable CI testing with multiple clusters using kind
  .travis.yml
  scripts/download-e2e-binaries.sh
  scripts/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#430 Remove manual install for federation.
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#435 Add option to skip download-binaries in pre-commit.sh
  .travis.yml
  scripts/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#424 Allow group and version to be specified for 'federate enable'
  pkg/kubefed2/federate/enable.go
  pkg/kubefed2/federate/util.go
  test/e2e/crd.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#440 Add images/federation-v2/controller-manager to git ignore
  .gitignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#441 Adds Service DNS documentation
  docs/images/servicedns-with-externaldns.png
  docs/servicedns-with-externaldns.md
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#431 always unjoin if any resource is failed in deletion
  pkg/kubefed2/unjoin.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#438 Remove excess code
  pkg/controller/sync/version/adapter.go
  pkg/controller/util/handlers.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#445 Added more detail for how to check if a joined cluster is ready.
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#443 Cleanup operation logic for namespaces in the host cluster
  pkg/controller/sync/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#379 Added Fed V2 concepts document.
  docs/concepts.md
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#446 Add scripts for creating and deleting kind clusters
  .travis.yml
  scripts/create-clusters.sh
  scripts/delete-clusters.sh
  scripts/download-e2e-binaries.sh
  scripts/pre-commit.sh
  scripts/util.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#323 Adds Multi-Cluster Ingress DNS documentation
  docs/images/ingressdns-with-externaldns.png
  docs/ingressdns-with-externaldns.md
  docs/userguide.md
  example/sample1/federatedingress-placement.yaml
  example/sample1/federatedingress-template.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#425 Add support for 'federate enable' to be configured from a file
  pkg/kubefed2/federate/directive.go
  pkg/kubefed2/federate/enable.go
  pkg/kubefed2/federate/util.go
  test/common/testobjects.go
  test/e2e/crd.go
  test/e2e/version.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#459 Minor fix for kind document.
  docs/environments/kind.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#453 Updates service dns doc to refer to issue 370 and gke clusters
  docs/servicedns-with-externaldns.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#458 Properly pluralizes type configs for resources ending in y
  pkg/apis/core/v1alpha1/federatedtypeconfig_types.go
  pkg/apis/core/v1alpha1/federatedtypeconfig_types_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S
