Repository kubernetes-sigs/kubefed, pull requests merged in 2019-01, with the labels that each got.

#537 fix e2e example in development.md and go version
  Makefile
  docs/development.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#532 Added issue template.
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/failing-test.md
  .github/ISSUE_TEMPLATE/support.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#540 Updated PR template file name to PULL_REQUEST_TEMPLATE.md.
  .github/PULL_REQUEST_TEMP.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#533 stop scheduler and plugins if resource is deleted
  pkg/controller/federatedtypeconfig/controller.go
  pkg/controller/schedulingmanager/controller.go
  pkg/controller/schedulingpreference/controller.go
  pkg/schedulingtypes/interface.go
  pkg/schedulingtypes/plugin.go
  pkg/schedulingtypes/replicascheduler.go
  pkg/schedulingtypes/typeregistry.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#542 Move multicluster dns sections to 'higher order behaviours'
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#539 Updated development guide for how to update toc.
  docs/development.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#541 tiny fix with gosimple
  pkg/controller/dnsendpoint/ingress_test.go
  pkg/controller/dnsendpoint/service_test.go
  pkg/controller/ingressdns/controller.go
  pkg/controller/servicedns/controller.go
  pkg/controller/status/controller.go
  pkg/controller/sync/controller.go
  pkg/controller/util/cluster_util.go
  pkg/controller/util/planner/planner.go
  pkg/kubefed2/federate/disable.go
  pkg/kubefed2/federate/enable.go
  pkg/kubefed2/join.go
  pkg/kubefed2/unjoin.go
  pkg/schedulingtypes/replicascheduler.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#544 Skip check of owner reference addition for namespaced resources
  test/e2e/version.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#527 Use a hash of the template field as the template version
  pkg/controller/sync/controller.go
  pkg/controller/sync/version/manager.go
  pkg/controller/sync/version/manager_test.go
  test/common/crudtester.go
  test/e2e/version.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#545 Require explicit namespace placement
  pkg/controller/federatedtypeconfig/controller.go
  pkg/controller/sync/controller.go
  pkg/controller/sync/placement/namespaced.go
  pkg/controller/sync/placement/plugin.go
  pkg/controller/sync/placement/resource.go
  pkg/controller/sync/placement/resource_test.go
  pkg/controller/util/constants.go
  pkg/controller/util/resourceclient.go
  pkg/controller/util/resourceinformer.go
  test/common/crudtester.go
  test/e2e/crud.go
  test/e2e/framework/framework.go
  test/e2e/framework/unmanaged.go
  test/e2e/ingressdns.go
  test/e2e/placement.go
  test/e2e/servicedns.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#519 DNS with external-dns based on CoreDNS in minikube
  docs/ingress-service-dns-with-coredns.md
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#561 docs: Fix broken links and typos
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#562 fix federation use default value to cover member cluster service node port when node port is auto-allocate by controller
  pkg/controller/sync/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#559 Ensure namespace placement changes trigger useful reconcile events
  pkg/controller/sync/controller.go
  pkg/controller/sync/placement/namespaced.go
  test/e2e/placement.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#548 Factor host cluster interaction out of the sync controller
  pkg/apis/core/typeconfig/interface.go
  pkg/apis/core/v1alpha1/federatedtypeconfig_types.go
  pkg/controller/federatedtypeconfig/controller.go
  pkg/controller/sync/accessor.go
  pkg/controller/sync/controller.go
  pkg/controller/sync/resource.go
  pkg/controller/sync/resource_test.go
  pkg/controller/sync/version/manager.go
  pkg/controller/util/deletionhelper/deletion_helper.go
  test/common/crudtester.go
  test/e2e/version.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL
