Repository kubernetes-sigs/kubefed, pull requests merged in 2019-09, with the labels that each got.

#1124 the equivalent APIs should be enabled at most once
  pkg/kubefedctl/enable/deprecatedapis.go
  pkg/kubefedctl/enable/deprecatedapis_test.go
  pkg/kubefedctl/enable/enable.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1135 Skip resources that don't have a valid DNS-1123 Subdomain name
  pkg/kubefedctl/federate/util.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1134 Delete and Recreate the KubeFedConfig on scope change.
  charts/kubefed/charts/controllermanager/templates/roles.yaml
  cmd/controller-manager/app/controller-manager.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1140 Add test to simulate control plane behavior for large numbers of clusters
  docs/development.md
  pkg/controller/sync/accessor.go
  pkg/controller/sync/controller.go
  pkg/controller/sync/dispatch/checkunmanaged.go
  pkg/controller/sync/dispatch/managed.go
  pkg/controller/sync/dispatch/unmanaged.go
  pkg/controller/sync/resource.go
  pkg/controller/util/federated_informer.go
  pkg/controller/util/naming.go
  pkg/kubefedctl/join.go
  test/common/crudtester.go
  test/e2e/e2e.go
  test/e2e/framework/framework.go
  test/e2e/framework/test_context.go
  test/e2e/scale.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1145 kubefedctl: Default --error-on-existing=true for join
  pkg/kubefedctl/join.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1149 Relax KubeFedCluster APIEndpoint validation
  pkg/apis/core/v1beta1/validation/validation.go
  pkg/apis/core/v1beta1/validation/validation_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1152 Allow setting custom kind image to create-servers.sh via KIND_IMAGE
  scripts/create-clusters.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1154 Return created kubefedcluster from JoinCluster
  pkg/kubefedctl/join.go
  test/e2e/scale.go
Labels: approved, cncf-cla: yes, lgtm, size/M
