Repository kubernetes-sigs/kubefed, pull requests merged in 2019-04, with the labels that each got.

#661 Accept group qualified type name for type in federate resource
  pkg/kubefed2/federate/federate.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#689 Refactor scheduling manager to correct goroutine usage
  cmd/controller-manager/app/controller-manager.go
  pkg/controller/schedulingmanager/controller.go
  pkg/controller/schedulingpreference/controller.go
  pkg/controller/util/safe_map.go
  pkg/schedulingtypes/interface.go
  pkg/schedulingtypes/replicascheduler.go
  test/e2e/framework/managed/controller.go
  test/e2e/scheduling.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#692 fix status controller not reconcile when federation has no readyCluster
  pkg/controller/status/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#712 Cleanup ci script
  scripts/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#673 Update crd test to use a permitted group/version
  pkg/kubefed2/enable/directive.go
  pkg/kubefed2/enable/enable.go
  test/e2e/crd.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#707 Refactor cluster field retention for reuse
  pkg/controller/sync/controller.go
  pkg/controller/sync/retain.go
  pkg/controller/sync/retain_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#710 make federation-role has enough permission for cluster-scope federation deployment
  charts/federation-v2/charts/controllermanager/templates/clusterrole.yaml
  scripts/deploy-federation.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#700 Update kind to 0.2.0
  scripts/create-clusters.sh
  scripts/delete-clusters.sh
  scripts/download-e2e-binaries.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#708 Simplify placement computation
  pkg/controller/sync/controller.go
  pkg/controller/sync/placement.go
  pkg/controller/sync/placement_test.go
  pkg/controller/sync/resource.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#719 Fix race conditions detected with in-memory execution of controllers
  pkg/controller/schedulingpreference/controller.go
  test/e2e/framework/unmanaged.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#675 Fix version manager race
  pkg/controller/sync/version/manager.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#713 Refactor sync controller reconcile loop
  pkg/controller/sync/accessor.go
  pkg/controller/sync/controller.go
  pkg/controller/sync/resource.go
  pkg/controller/sync/updater.go
  pkg/controller/util/federated_updater.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#725 add xunpan as reviewer after discussed with marun
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#717 apply FederationConfig to set controller options
  cmd/controller-manager/app/controller-manager.go
  example/config/federationconfig.yaml
  pkg/apis/core/v1alpha1/federationconfig_types.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/util/cluster_util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#560 Added additionalprintercolumn "Ready" for the federatedcluster
  charts/federation-v2/charts/controllermanager/templates/crds.yaml
  pkg/apis/core/v1alpha1/federatedcluster_types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#714 Switch to having the FederatedNamespace define the template
  CHANGELOG.md
  charts/federation-v2/templates/crds.yaml
  pkg/controller/sync/controller.go
  pkg/controller/sync/resource.go
  pkg/controller/sync/resource_test.go
  pkg/kubefed2/enable/enable.go
  test/common/crudtester.go
  test/e2e/version.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#736 Replace managed fixture test suite with in-memory suite
  Gopkg.lock
  docs/development.md
  scripts/pre-commit.sh
  test/e2e/crud.go
  test/e2e/e2e.go
  test/e2e/framework/cluster.go
  test/e2e/framework/controller.go
  test/e2e/framework/enable.go
  test/e2e/framework/framework.go
  test/e2e/framework/managed.go
  test/e2e/framework/managed/federation.go
  test/e2e/framework/managed/kubeapi.go
  test/e2e/framework/managed/logger.go
  test/e2e/framework/managed/secureconfig.go
  test/e2e/framework/managed/util.go
  test/e2e/framework/test_context.go
  test/e2e/framework/unmanaged.go
  test/e2e/framework/util.go
  test/e2e/ingressdns.go
  test/e2e/leaderelection.go
  test/e2e/scheduling.go
  test/e2e/servicedns.go
  test/e2e/version.go
  vendor/github.com/onsi/gomega/gbytes/buffer.go
  vendor/github.com/onsi/gomega/gbytes/io_wrappers.go
  vendor/github.com/onsi/gomega/gbytes/say_matcher.go
  vendor/github.com/onsi/gomega/gexec/build.go
  vendor/github.com/onsi/gomega/gexec/exit_matcher.go
  vendor/github.com/onsi/gomega/gexec/prefixed_writer.go
  vendor/github.com/onsi/gomega/gexec/session.go
  vendor/sigs.k8s.io/testing_frameworks/LICENSE
  vendor/sigs.k8s.io/testing_frameworks/integration/addr/manager.go
  vendor/sigs.k8s.io/testing_frameworks/integration/apiserver.go
  vendor/sigs.k8s.io/testing_frameworks/integration/control_plane.go
  vendor/sigs.k8s.io/testing_frameworks/integration/doc.go
  vendor/sigs.k8s.io/testing_frameworks/integration/etcd.go
  vendor/sigs.k8s.io/testing_frameworks/integration/internal/apiserver.go
  vendor/sigs.k8s.io/testing_frameworks/integration/internal/arguments.go
  vendor/sigs.k8s.io/testing_frameworks/integration/internal/bin_path_finder.go
  vendor/sigs.k8s.io/testing_frameworks/integration/internal/etcd.go
  vendor/sigs.k8s.io/testing_frameworks/integration/internal/process.go
  vendor/sigs.k8s.io/testing_frameworks/integration/kubectl.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#727 Remove mention of script-based install from the user guide
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#662 Make federate resource usable without federation API
  pkg/kubefed2/enable/enable.go
  pkg/kubefed2/enable/util.go
  pkg/kubefed2/federate/federate.go
  test/e2e/federate.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#742 Kubefed2 Federate fixes
  pkg/kubefed2/disable.go
  pkg/kubefed2/enable/enable.go
  pkg/kubefed2/federate/federate.go
  pkg/kubefed2/federate/util.go
  pkg/kubefed2/join.go
  pkg/kubefed2/unjoin.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#752 Truncate changelog after releasing v0.0.8
  CHANGELOG.md
Labels: approved, cncf-cla: yes, size/XS

#744 kubefed2 enable succeeds if federation of the type already enabled
  pkg/kubefed2/enable/enable.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#739 Cleanup kubefed2 subcommand options
  pkg/kubefed2/disable.go
  pkg/kubefed2/enable/enable.go
  pkg/kubefed2/federate/federate.go
  pkg/kubefed2/join.go
  pkg/kubefed2/options/options.go
  pkg/kubefed2/unjoin.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#757 Fix CI fail when there has daemon.json already
  scripts/create-clusters.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#754 Add chart index to support installing the released chart
  charts/index.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#758 clean obsolete script to delete clusterrolebinding federation-admin
  scripts/delete-federation.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#734 Make deploy-federation.sh more robust
  scripts/deploy-federation.sh
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#715 Only watched managed resources
  CHANGELOG.md
  pkg/controller/sync/controller.go
  pkg/controller/sync/resource.go
  pkg/controller/sync/updater.go
  pkg/controller/sync/version/manager.go
  pkg/controller/util/federated_informer.go
  pkg/controller/util/resourceinformer.go
  test/common/crudtester.go
  test/common/dns.go
  test/e2e/crud.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#767 Give controller cluster role ability to patch
  charts/federation-v2/charts/controllermanager/templates/clusterrole.yaml
  charts/federation-v2/charts/controllermanager/templates/role.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#737 apply federationconfig in chart and remove useless command line options of controller
  CHANGELOG.md
  charts/federation-v2/README.md
  charts/federation-v2/charts/controllermanager/templates/deployment.yaml
  charts/federation-v2/charts/controllermanager/templates/federationconfig.yaml
  charts/federation-v2/values.yaml
  cmd/controller-manager/app/controller-manager.go
  cmd/controller-manager/app/options/options.go
  config/federationconfig.yaml
  pkg/apis/core/v1alpha1/federationconfig_types.go
  pkg/controller/util/cluster_util.go
  test/e2e/leaderelection.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#663 Implement optional --enable-type in federate resource
  pkg/kubefed2/federate/federate.go
  test/e2e/federate.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#772 user federation-controller sa instead of the default one
  charts/federation-v2/charts/controllermanager/templates/clusterrolebindings.yaml
  charts/federation-v2/charts/controllermanager/templates/deployment.yaml
  charts/federation-v2/charts/controllermanager/templates/rolebindings.yaml
  charts/federation-v2/charts/controllermanager/templates/serviceaccout.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#755 Improve reliability of cluster health check
  charts/federation-v2/README.md
  charts/federation-v2/charts/controllermanager/templates/federationconfig.yaml
  charts/federation-v2/values.yaml
  cmd/controller-manager/app/controller-manager.go
  cmd/controller-manager/app/options/options.go
  pkg/apis/core/v1alpha1/federationconfig_types.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/federatedcluster/clusterclient.go
  pkg/controller/federatedcluster/controller.go
  pkg/controller/federatedcluster/controller_test.go
  pkg/controller/util/cluster_util.go
  pkg/controller/util/controllerconfig.go
  pkg/controller/util/federated_informer.go
  test/e2e/framework/cluster.go
  test/e2e/framework/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#768 Add PRs to changelog
  CHANGELOG.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#779 Add imagePullPolicy to helm chart controllermanager deployment template
  charts/federation-v2/.helmignore
  charts/federation-v2/README.md
  charts/federation-v2/charts/controllermanager/templates/deployment.yaml
  charts/federation-v2/values.yaml
  scripts/deploy-federation.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#786 Fix sync controller import ordering
  pkg/controller/sync/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#780 [Makefile] fix `make` compilation error on macOS
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#787 Remove host-only docker daemon config file check
  scripts/create-clusters.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#788 Add helpers to [ check for | add | remove ] the managed label
  pkg/controller/sync/resource.go
  pkg/controller/sync/updater.go
  pkg/controller/util/managedlabel.go
  pkg/controller/util/resourceinformer.go
  test/common/crudtester.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#792 adding Age column while listing the cluster status
  charts/federation-v2/charts/controllermanager/templates/crds.yaml
  pkg/apis/core/v1alpha1/federatedcluster_types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#797 Extend service discovery for multi-zone clusters
  CHANGELOG.md
  charts/federation-v2/charts/controllermanager/templates/crds.yaml
  pkg/apis/core/v1alpha1/federatedcluster_types.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/multiclusterdns/v1alpha1/servicednsrecord_types.go
  pkg/apis/multiclusterdns/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/dnsendpoint/service.go
  pkg/controller/dnsendpoint/service_test.go
  pkg/controller/federatedcluster/clusterclient.go
  pkg/controller/federatedcluster/controller.go
  pkg/controller/servicedns/controller.go
  test/e2e/servicedns.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#793 Update instructions for chart release and installation.
  charts/federation-v2/README.md
  docs/releasing.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#765 A script to fix up the configuration for k3s
  scripts/fix-ca-for-k3s.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#771 support optional values in FederationConfig
  cmd/controller-manager/app/controller-manager.go
  cmd/controller-manager/app/options/options.go
  config/federationconfig.yaml
  pkg/controller/util/cluster_util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#775 get option from FederationConfig instead of specified in command line
  docs/userguide.md
  pkg/kubefed2/join.go
  pkg/kubefed2/options/options.go
  pkg/kubefed2/unjoin.go
  scripts/delete-federation.sh
  scripts/deploy-federation.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#785 Refactor updater for extensibility
  pkg/controller/sync/accessor.go
  pkg/controller/sync/controller.go
  pkg/controller/sync/dispatch/managed.go
  pkg/controller/sync/dispatch/operation.go
  pkg/controller/sync/dispatch/retain.go
  pkg/controller/sync/dispatch/retain_test.go
  pkg/controller/sync/resource.go
  pkg/controller/sync/updater.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#790 add golangci lint to travis
  .golangci.yml
  .travis.yml
  cmd/hyperfed/main.go
  pkg/controller/dnsendpoint/controller.go
  pkg/controller/schedulingmanager/controller.go
  pkg/controller/schedulingpreference/controller.go
  pkg/controller/servicedns/controller.go
  pkg/controller/sync/dispatch/retain_test.go
  pkg/controller/sync/placement_test.go
  pkg/controller/sync/resource.go
  pkg/controller/util/cluster_util.go
  pkg/controller/util/federated_updater.go
  pkg/controller/util/meta.go
  pkg/controller/util/planner/planner.go
  pkg/controller/util/planner/planner_test.go
  pkg/controller/util/podanalyzer/pod_helper_test.go
  pkg/features/features.go
  pkg/kubefed2/disable.go
  pkg/kubefed2/enable/enable.go
  pkg/kubefed2/join.go
  pkg/kubefed2/kubefed2.go
  pkg/kubefed2/unjoin.go
  pkg/schedulingtypes/plugin.go
  pkg/schedulingtypes/replicascheduler.go
  test/common/crudtester.go
  test/e2e/crud.go
  test/e2e/framework/framework.go
  test/e2e/framework/unmanaged.go
  test/e2e/ingressdns.go
  test/e2e/servicedns.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#776 uses scope instead of limitedScope
  CHANGELOG.md
  charts/federation-v2/README.md
  charts/federation-v2/charts/clusterregistry/templates/crds.yaml
  charts/federation-v2/charts/controllermanager/templates/clusterrole.yaml
  charts/federation-v2/charts/controllermanager/templates/clusterrolebindings.yaml
  charts/federation-v2/charts/controllermanager/templates/crds.yaml
  charts/federation-v2/charts/controllermanager/templates/deployment.yaml
  charts/federation-v2/charts/controllermanager/templates/federationconfig.yaml
  charts/federation-v2/charts/controllermanager/templates/role.yaml
  charts/federation-v2/charts/controllermanager/templates/rolebindings.yaml
  charts/federation-v2/templates/crds.yaml
  charts/federation-v2/values.yaml
  cmd/controller-manager/app/controller-manager.go
  cmd/controller-manager/app/options/options.go
  example/config/federationconfig.yaml
  pkg/apis/core/v1alpha1/federationconfig_types.go
  pkg/kubefed2/join.go
  pkg/kubefed2/options/options.go
  scripts/deploy-federation.sh
  scripts/sync-up-helm-chart.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#796 update RBAC with more detailed permission
  charts/federation-v2/charts/controllermanager/templates/clusterrole.yaml
  charts/federation-v2/charts/controllermanager/templates/role.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#789 Factor unmanaged dispatcher out of the managed dispatcher
  pkg/controller/sync/dispatch/managed.go
  pkg/controller/sync/dispatch/operation.go
  pkg/controller/sync/dispatch/unmanaged.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#808 Release v0.0.9
  CHANGELOG.md
  charts/index.yaml
  docs/releasing.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#806 FederatedCluster should use strongly-typed reference to 'Cluster'
  charts/federation-v2/charts/controllermanager/templates/crds.yaml
  pkg/apis/core/v1alpha1/federatedcluster_types.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/kubefed2/join.go
Labels: approved, cncf-cla: yes, lgtm, size/S
