Repository kubernetes-sigs/kubefed, pull requests merged in 2019-03, with the labels that each got.

#620 Build a Scheme for generic client at init time
  pkg/apis/register.go
  pkg/client/generic/genericclient.go
  pkg/client/generic/scheme/register.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#600 Log improvements
  pkg/controller/federatedcluster/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#624 Fix races in version manager and generic client construction
  pkg/client/generic/genericclient.go
  pkg/controller/sync/version/adapter.go
  pkg/controller/sync/version/cluster.go
  pkg/controller/sync/version/manager.go
  pkg/controller/sync/version/namespaced.go
  test/common/crudtester.go
  test/e2e/framework/unmanaged.go
  test/e2e/version.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#615 Add shortnames prefixed with f when enabling a type
  charts/federation-v2/templates/configmaps.yaml
  charts/federation-v2/templates/deployments.apps.yaml
  charts/federation-v2/templates/ingresses.extensions.yaml
  charts/federation-v2/templates/namespaces.yaml
  charts/federation-v2/templates/replicasets.apps.yaml
  charts/federation-v2/templates/serviceaccounts.yaml
  charts/federation-v2/templates/services.yaml
  pkg/kubefed2/enable/enable.go
  pkg/kubefed2/enable/util.go
  scripts/pre-commit.sh
  test/e2e/crd.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#621 deploy-federation.sh: Wait for the propagation of clusterregistry CRD
  scripts/deploy-federation.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#627 make log level lower to consist with reconcile message
  pkg/controller/federatedtypeconfig/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#634 Fix Boilerplate issues
  .travis.yml
  Makefile
  cmd/kubefed2/kubefed2.go
  hack/boilerplate.go.txt
  pkg/apis/core/v1alpha1/zz_generated.kubebuilder.go
  pkg/apis/multiclusterdns/doc.go
  pkg/apis/multiclusterdns/v1alpha1/doc.go
  pkg/apis/multiclusterdns/v1alpha1/zz_generated.kubebuilder.go
  pkg/apis/scheduling/v1alpha1/zz_generated.kubebuilder.go
  pkg/controller/doc.go
  pkg/controller/ingressdns/controller.go
  pkg/controller/schedulingpreference/controller.go
  pkg/controller/servicedns/controller.go
  pkg/controller/sharedinformers/doc.go
  pkg/doc.go
  pkg/inject/zz_generated.kubebuilder.go
  pkg/kubefed2/unjoin.go
  test/e2e/scheduling.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#626 Fix races in replica scheduling code
  pkg/controller/schedulingmanager/controller.go
  pkg/controller/util/safe_map.go
  pkg/schedulingtypes/replicascheduler.go
  scripts/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#632 Add leader election to controller-manager
  Gopkg.lock
  cmd/controller-manager/app/controller-manager.go
  cmd/controller-manager/app/leaderelection/leaderelection.go
  cmd/controller-manager/app/options/options.go
  pkg/controller/util/cluster_util.go
  pkg/controller/util/controllerconfig.go
  test/e2e/leaderelection.go
  vendor/github.com/kubernetes-sigs/kubebuilder/pkg/test/doc.go
  vendor/github.com/kubernetes-sigs/kubebuilder/pkg/test/ginkgo.go
  vendor/github.com/kubernetes-sigs/kubebuilder/pkg/test/server.go
  vendor/k8s.io/apimachinery/pkg/util/uuid/uuid.go
  vendor/k8s.io/client-go/tools/leaderelection/healthzadaptor.go
  vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/endpointslock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/interface.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#644 Updated toc for userguide.
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#635 Handle events with DeletedFinalStateUnknown
  pkg/controller/util/handlers.go
  pkg/controller/util/handlers_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#645 Fix leader election e2e test
  cmd/controller-manager/app/controller-manager.go
  cmd/controller-manager/app/leaderelection/leaderelection.go
  test/e2e/leaderelection.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#646 Update kube-openapi to include compatibility fixes required by openshift
  Gopkg.lock
  vendor/k8s.io/kube-openapi/pkg/util/proto/document.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/openapi.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#587 Enable configurable replicas retention by the sync controller
  charts/federation-v2/templates/deployments.apps.yaml
  charts/federation-v2/templates/replicasets.apps.yaml
  docs/userguide.md
  pkg/controller/sync/controller.go
  pkg/controller/sync/controller_test.go
  pkg/controller/util/constants.go
  pkg/kubefed2/enable/validation.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#628 support federated resource CRD sharing for namespaced installation
  pkg/kubefed2/enable/enable.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#649 User guide doesn't cover `unjoin`
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#657 Replace statefulset with deployment for controller-manager.
  charts/federation-v2/charts/controllermanager/templates/deployment.yaml
  charts/federation-v2/charts/controllermanager/templates/service.yaml
  charts/federation-v2/values.yaml
  cmd/controller-manager/app/controller-manager.go
  cmd/controller-manager/app/options/options.go
  docs/development.md
  hack/install-latest.yaml
  pkg/controller/util/controllerconfig.go
  scripts/delete-federation.sh
  scripts/generate-install-yaml.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#629 support cluster RBAC for namespaced installation
  pkg/kubefed2/join.go
  pkg/kubefed2/unjoin.go
  pkg/kubefed2/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#650 Some OSX support
  Makefile
  scripts/download-binaries.sh
  scripts/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#664 Remove invalid option from `kubefed2 enable` example
  pkg/kubefed2/enable/enable.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#651 Update diagrams after API unification
  README.md
  docs/images/concepts.png
  docs/images/propagation.png
Labels: approved, cncf-cla: yes, lgtm, size/XS

#659 check if namespace exist or not before creating resources in federation enable
  pkg/kubefed2/enable/enable.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#630 support multiple namespaced federation with script
  scripts/delete-federation.sh
  scripts/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#631 support multiple namespaced federation with helm
  charts/federation-v2/charts/clusterregistry/templates/crds.yaml
  charts/federation-v2/charts/controllermanager/templates/clusterrole.yaml
  charts/federation-v2/charts/controllermanager/templates/clusterrolebindings.yaml
  charts/federation-v2/charts/controllermanager/templates/crds.yaml
  charts/federation-v2/charts/controllermanager/templates/deployment.yaml
  charts/federation-v2/charts/controllermanager/templates/role.yaml
  charts/federation-v2/charts/controllermanager/templates/rolebindings.yaml
  charts/federation-v2/templates/clusterroles.rbac.authorization.k8s.io.yaml
  charts/federation-v2/templates/configmaps.yaml
  charts/federation-v2/templates/crds.yaml
  charts/federation-v2/templates/deployments.apps.yaml
  charts/federation-v2/templates/federatedtypeconfig.yaml
  charts/federation-v2/templates/ingresses.extensions.yaml
  charts/federation-v2/templates/jobs.batch.yaml
  charts/federation-v2/templates/namespaces.yaml
  charts/federation-v2/templates/replicasets.apps.yaml
  charts/federation-v2/templates/secrets.yaml
  charts/federation-v2/templates/serviceaccounts.yaml
  charts/federation-v2/templates/services.yaml
  charts/federation-v2/values.yaml
  scripts/delete-federation.sh
  scripts/deploy-federation.sh
  scripts/sync-up-helm-chart.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#667 Fix namespace deletion handling
  pkg/controller/sync/resource.go
  pkg/controller/util/deletionhelper/deletion_helper.go
  test/common/crudtester.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#666 Ensure all script boolean handling uses y/<empty> vs true/false
  scripts/delete-federation.sh
  scripts/deploy-federation.sh
  scripts/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#671 Fix helm chart rules to allow types instead of primitives
  charts/federation-v2/charts/controllermanager/templates/clusterrole.yaml
  charts/federation-v2/charts/controllermanager/templates/role.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#674 update document for namespaced federation
  charts/federation-v2/README.md
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#647 Refactor federate resource to simplify crud tests
  pkg/kubefed2/federate/federate.go
  test/common/crudtester.go
  test/common/resource_helper.go
  test/common/testobjects.go
  test/e2e/crud.go
  test/e2e/federate.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#679 Fix binary name break in scripts/imagebuild.sh
  scripts/imagebuild.sh
Labels: approved, cncf-cla: yes, size/XS

#686 e2eLogger: Make the summary a little more useful
  test/e2e/framework/logger.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#682 Fix help text typo in enable.go
  pkg/kubefed2/enable/enable.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#684 build improvements
  Makefile
  cmd/kubefed2/main.go
  scripts/deploy-federation.sh
  scripts/imagebuild.sh
  scripts/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#691 Integrating fmt update in makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#696 Fix a typo in userguide
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#685 add FederatedConfig resource
  charts/federation-v2/charts/controllermanager/templates/crds.yaml
  example/config/federationconfig.yaml
  hack/install-latest.yaml
  pkg/apis/core/v1alpha1/federationconfig_types.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1alpha1/zz_generated.kubebuilder.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/core_client.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_core_client.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_federationconfig.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/federationconfig.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/generated_expansion.go
  pkg/client/informers/externalversions/core/v1alpha1/federationconfig.go
  pkg/client/informers/externalversions/core/v1alpha1/interface.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/core/v1alpha1/expansion_generated.go
  pkg/client/listers/core/v1alpha1/federationconfig.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#698 Fix retain replicas field type (was bool, should be boolean)
  CHANGELOG.md
  charts/federation-v2/templates/crds.yaml
  pkg/kubefed2/enable/validation.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#704 Fix invalid table format in userguide
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#703 Adding the missing shebang statement
  hack/verify-errpkg.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#660 Implement -o yaml for federate resource
  pkg/kubefed2/enable/enable.go
  pkg/kubefed2/federate/federate.go
  pkg/kubefed2/federate/util.go
  pkg/kubefed2/util/yaml_writer.go
  test/e2e/federate.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#683 make federation-role has enough permission for namespaced deployment
  charts/federation-v2/charts/controllermanager/templates/role.yaml
  scripts/deploy-federation.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#669 Fix orphan deletion
  CHANGELOG.md
  docs/userguide.md
  pkg/controller/sync/controller.go
  pkg/controller/sync/resource.go
  pkg/controller/util/deletionhelper/deletion_helper.go
  test/common/crudtester.go
  test/e2e/crd.go
  test/e2e/crud.go
  test/e2e/placement.go
Labels: approved, cncf-cla: yes, lgtm, size/L
