Repository kubernetes-sigs/kubefed, pull requests merged in 2019-02, with the labels that each got.

#534 kubefed2 `federate enable/disable` -> kubefed2 `enable/disable`
  pkg/kubefed2/federate/disable.go
  pkg/kubefed2/federate/enable.go
  pkg/kubefed2/federate/federate.go
  pkg/kubefed2/kubefed2.go
  scripts/delete-federation.sh
  scripts/deploy-federation.sh
  scripts/sync-up-helm-chart.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#569 Simple overrides unmarshalling
  pkg/controller/util/overrides.go
  pkg/schedulingtypes/plugin.go
  test/common/crudtester.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#571 Update docs and comments for 'federate enable/disable'
  docs/userguide.md
  pkg/kubefed2/federate/disable.go
  pkg/kubefed2/federate/enable.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#572 s/FederateDirective/EnableTypeDirective
  config/enabletypedirectives/clusterroles.rbac.authorization.k8s.io.yaml
  config/enabletypedirectives/configmaps.yaml
  config/enabletypedirectives/deployments.apps.yaml
  config/enabletypedirectives/ingresses.extensions.yaml
  config/enabletypedirectives/jobs.batch.yaml
  config/enabletypedirectives/namespaces.yaml
  config/enabletypedirectives/replicasets.apps.yaml
  config/enabletypedirectives/secrets.yaml
  config/enabletypedirectives/serviceaccounts.yaml
  config/enabletypedirectives/services.yaml
  pkg/kubefed2/federate/directive.go
  pkg/kubefed2/federate/enable.go
  scripts/check-directive-fixtures.sh
  scripts/deploy-federation.sh
  scripts/sync-up-helm-chart.sh
  test/e2e/crd.go
  test/e2e/framework/managed/federation.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#590 download-binaries.sh: Remove a problematic pipefail
  scripts/download-binaries.sh
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#595 Fix unjoin to use namespace identity instead of context name as criteria for removal
  pkg/kubefed2/unjoin.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#578 Add --host-cluster-name to kubefed2 join to override use of kubeconfig context name for resources
  pkg/kubefed2/join.go
  pkg/kubefed2/unjoin.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#584 Skip Travis build for doc-only changes
  .travis.yml
  hack/verify-docfiles.sh
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#594 build kubefed2 on demands with parameter control
  scripts/pre-commit.sh
  scripts/sync-up-helm-chart.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#601 Fix service account sync
  charts/federation-v2/templates/serviceaccounts.yaml
  config/enabletypedirectives/serviceaccounts.yaml
  pkg/controller/sync/controller.go
  pkg/controller/util/constants.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#596 forcely delete a member cluster information in the host cluster
  pkg/kubefed2/unjoin.go
  pkg/kubefed2/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#602 Implement a generic informer
  cmd/controller-manager/app/controller-manager.go
  pkg/controller/federatedtypeconfig/controller.go
  pkg/controller/util/genericinformer.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#586 Determine the comparison field at runtime rather than configuring
  charts/federation-v2/charts/controllermanager/templates/crds.yaml
  charts/federation-v2/templates/clusterroles.rbac.authorization.k8s.io.yaml
  charts/federation-v2/templates/configmaps.yaml
  charts/federation-v2/templates/deployments.apps.yaml
  charts/federation-v2/templates/ingresses.extensions.yaml
  charts/federation-v2/templates/jobs.batch.yaml
  charts/federation-v2/templates/namespaces.yaml
  charts/federation-v2/templates/replicasets.apps.yaml
  charts/federation-v2/templates/secrets.yaml
  charts/federation-v2/templates/serviceaccounts.yaml
  charts/federation-v2/templates/services.yaml
  config/enabletypedirectives/deployments.apps.yaml
  config/enabletypedirectives/ingresses.extensions.yaml
  config/enabletypedirectives/jobs.batch.yaml
  config/enabletypedirectives/replicasets.apps.yaml
  hack/install-latest.yaml
  pkg/apis/core/typeconfig/interface.go
  pkg/apis/core/v1alpha1/federatedtypeconfig_types.go
  pkg/apis/core/v1alpha1/zz_generated.kubebuilder.go
  pkg/controller/sync/controller.go
  pkg/controller/util/propagatedversion.go
  pkg/kubefed2/federate/directive.go
  pkg/kubefed2/federate/enable.go
  test/common/crudtester.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#599 Replace references to 'federation primitives' with 'federated type'
  charts/federation-v2/templates/clusterroles.rbac.authorization.k8s.io.yaml
  charts/federation-v2/templates/configmaps.yaml
  charts/federation-v2/templates/deployments.apps.yaml
  charts/federation-v2/templates/ingresses.extensions.yaml
  charts/federation-v2/templates/jobs.batch.yaml
  charts/federation-v2/templates/namespaces.yaml
  charts/federation-v2/templates/replicasets.apps.yaml
  charts/federation-v2/templates/secrets.yaml
  charts/federation-v2/templates/serviceaccounts.yaml
  charts/federation-v2/templates/services.yaml
  docs/userguide.md
  example/sample1/federatedclusterrole.yaml
  example/sample1/federatedclusterrolebinding.yaml
  example/sample1/federatedconfigmap.yaml
  example/sample1/federateddeployment.yaml
  example/sample1/federatedingress.yaml
  example/sample1/federatedjob.yaml
  example/sample1/federatednamespace.yaml
  example/sample1/federatedsecret.yaml
  example/sample1/federatedservice.yaml
  example/sample1/federatedserviceaccount.yaml
  pkg/apis/core/v1alpha1/federatedtypeconfig_types.go
  pkg/controller/sync/accessor.go
  pkg/controller/sync/resource.go
  pkg/kubefed2/federate/directive.go
  pkg/kubefed2/federate/enable.go
  test/e2e/crd.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#609 use new federatedservice.yaml file in service dns document
  docs/ingress-service-dns-with-coredns.md
  docs/servicedns-with-externaldns.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#555 Allow join command to run in idempotent mode
  pkg/kubefed2/join.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#604 Avoid using generated client for federation types and use generic client instead
  cmd/controller-manager/app/controller-manager.go
  pkg/apis/register.go
  pkg/client/generic/genericclient.go
  pkg/controller/dnsendpoint/controller.go
  pkg/controller/dnsendpoint/ingress.go
  pkg/controller/dnsendpoint/service.go
  pkg/controller/federatedcluster/controller.go
  pkg/controller/federatedtypeconfig/controller.go
  pkg/controller/ingressdns/controller.go
  pkg/controller/schedulingmanager/controller.go
  pkg/controller/schedulingpreference/controller.go
  pkg/controller/servicedns/controller.go
  pkg/controller/status/controller.go
  pkg/controller/sync/accessor.go
  pkg/controller/sync/controller.go
  pkg/controller/sync/version/adapter.go
  pkg/controller/sync/version/cluster.go
  pkg/controller/sync/version/manager.go
  pkg/controller/sync/version/namespaced.go
  pkg/controller/util/controllerconfig.go
  pkg/controller/util/federated_informer.go
  pkg/controller/util/genericinformer.go
  pkg/kubefed2/federate/disable.go
  pkg/kubefed2/federate/enable.go
  pkg/kubefed2/join.go
  pkg/kubefed2/unjoin.go
  pkg/kubefed2/util/util.go
  pkg/schedulingtypes/interface.go
  pkg/schedulingtypes/plugin.go
  pkg/schedulingtypes/replicascheduler.go
  test/common/crudtester.go
  test/common/dns.go
  test/e2e/framework/framework.go
  test/e2e/framework/managed.go
  test/e2e/framework/managed/cluster.go
  test/e2e/framework/managed/federation.go
  test/e2e/framework/unmanaged.go
  test/e2e/ingressdns.go
  test/e2e/scheduling.go
  test/e2e/servicedns.go
  test/e2e/version.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#547 add test case for scheduler manager
  cmd/controller-manager/app/controller-manager.go
  pkg/controller/schedulingmanager/controller.go
  test/e2e/framework/managed/controller.go
  test/e2e/framework/managed/federation.go
  test/e2e/scheduling.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#610 Short name support in kubefed2 disable and reject case if multiple resource name matched
  pkg/kubefed2/federate/disable.go
  pkg/kubefed2/federate/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#616 Remove typed client usage
  pkg/apis/core/v1alpha1/clusterpropagatedversion_types_test.go
  pkg/apis/core/v1alpha1/federatedcluster_types_test.go
  pkg/apis/core/v1alpha1/federatedservicestatus_types_test.go
  pkg/apis/core/v1alpha1/federatedtypeconfig_types_test.go
  pkg/apis/core/v1alpha1/propagatedversion_types_test.go
  pkg/apis/core/v1alpha1/v1alpha1_suite_test.go
  pkg/apis/multiclusterdns/v1alpha1/dnsendpoint_types_test.go
  pkg/apis/multiclusterdns/v1alpha1/domain_types_test.go
  pkg/apis/multiclusterdns/v1alpha1/ingressdnsrecord_types_test.go
  pkg/apis/multiclusterdns/v1alpha1/servicednsrecord_types_test.go
  pkg/apis/multiclusterdns/v1alpha1/v1alpha1_suite_test.go
  pkg/apis/scheduling/v1alpha1/replicaschedulingpreference_types_test.go
  pkg/apis/scheduling/v1alpha1/v1alpha1_suite_test.go
  pkg/client/generic/genericclient.go
  pkg/controller/federatedcluster/clusterclient.go
  pkg/controller/federatedcluster/controller.go
  pkg/controller/ingressdns/controller.go
  pkg/controller/servicedns/controller.go
  pkg/controller/status/controller.go
  pkg/controller/sync/controller.go
  pkg/controller/util/cluster_util.go
  pkg/controller/util/controllerconfig.go
  pkg/controller/util/federated_informer.go
  pkg/kubefed2/join.go
  pkg/kubefed2/unjoin.go
  pkg/kubefed2/util/util.go
  pkg/schedulingtypes/plugin.go
  pkg/schedulingtypes/replicascheduler.go
  test/e2e/framework/framework.go
  test/e2e/framework/managed.go
  test/e2e/framework/managed/federation.go
  test/e2e/framework/unmanaged.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#607 Federate resource
  pkg/controller/sync/placement_test.go
  pkg/controller/sync/resource_test.go
  pkg/controller/util/constants.go
  pkg/kubefed2/disable.go
  pkg/kubefed2/enable/directive.go
  pkg/kubefed2/enable/enable.go
  pkg/kubefed2/enable/schema.go
  pkg/kubefed2/enable/util.go
  pkg/kubefed2/enable/validation.go
  pkg/kubefed2/federate/federate.go
  pkg/kubefed2/federate/util.go
  pkg/kubefed2/kubefed2.go
  test/common/crudtester.go
  test/common/fixtures.go
  test/common/testobjects.go
  test/common/typeconfig.go
  test/e2e/crd.go
  test/e2e/crud.go
  test/e2e/framework/managed/federation.go
  test/e2e/placement.go
  test/e2e/scheduling.go
  test/e2e/version.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#566 Add feature matrix to README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S
