Repository kubernetes-sigs/kubefed, pull requests merged in 2019-07, with the labels that each got.

#1017 Fixup override docs and validation
  charts/kubefed/templates/crds.yaml
  docs/userguide.md
  pkg/kubefedctl/enable/validation.go
  scripts/sync-up-helm-chart.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1018 Address comments from PR 1012
  pkg/controller/federatedtypeconfig/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1023 Removed outdated script reference
  docs/installation.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1033 Fix typo in user guide
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1026 Always adopt resources for FederatedNamespace in host cluster
  pkg/controller/sync/dispatch/managed.go
  pkg/controller/sync/resource.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1025 fix dns endpoint controller merged two different type record's targets with same dns name
  pkg/controller/dnsendpoint/common.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1038 Remove generation of the template validation schema
  CHANGELOG.md
  charts/kubefed/templates/crds.yaml
  pkg/kubefedctl/enable/validation.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#980 Update kind to v0.3.0
  scripts/create-clusters.sh
  scripts/download-e2e-binaries.sh
  scripts/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1015 Add KubeFedConfig defaulting via mutating admission webhook
  CHANGELOG.md
  cmd/controller-manager/app/controller-manager.go
  config/kubefedconfig.yaml
  pkg/apis/core/v1beta1/defaults/defaults.go
  pkg/apis/core/v1beta1/defaults/defaults_test.go
  pkg/apis/core/v1beta1/validation/validation_test.go
  pkg/controller/util/cluster_util.go
  pkg/controller/webhook/kubefedconfig/webhook.go
  pkg/features/features.go
  test/common/dns.go
  test/e2e/defaulting.go
  test/e2e/framework/controller.go
  test/e2e/framework/wait.go
  test/e2e/ingressdns.go
  test/e2e/leaderelection.go
  test/e2e/servicedns.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1010 Always retain metadata.finalizers and metadata.annotations
  CHANGELOG.md
  docs/userguide.md
  pkg/controller/sync/dispatch/managed.go
  pkg/controller/sync/dispatch/retain.go
  pkg/controller/sync/resource.go
  pkg/controller/sync/status/status.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1043 Update the links of the features in the README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1008 Implement orphaning-deletion commands
  CHANGELOG.md
  docs/userguide.md
  pkg/controller/sync/controller.go
  pkg/controller/util/orphaninganotation.go
  pkg/kubefedctl/federate/federate.go
  pkg/kubefedctl/federate/util.go
  pkg/kubefedctl/kubefedctl.go
  pkg/kubefedctl/orphaning/disable.go
  pkg/kubefedctl/orphaning/enable.go
  pkg/kubefedctl/orphaning/orphaning.go
  pkg/kubefedctl/orphaning/status.go
  pkg/kubefedctl/util/util.go
  test/common/crudtester.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#880 Set kubefed-namespace via the config mechanism for in-cluster deployment
  charts/kubefed/charts/controllermanager/templates/deployments.yaml
  cmd/controller-manager/app/controller-manager.go
  cmd/controller-manager/app/options/options.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1028 controller/kubefedcluster: fixes for delete handling and suppress changes due to status updates
  pkg/controller/kubefedcluster/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1027 Validation for KubeFedCluster API
  CHANGELOG.md
  charts/kubefed/charts/controllermanager/templates/webhook.yaml
  pkg/apis/core/v1beta1/validation/validation.go
  pkg/apis/core/v1beta1/validation/validation_test.go
  pkg/controller/webhook/kubefedcluster/webhook.go
  test/common/validation.go
  test/e2e/validation.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1039 Fix build on other Linux architectures
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#1045 Resolve target namespace from the client kubeconfig context
  CHANGELOG.md
  docs/userguide.md
  pkg/kubefedctl/federate/federate.go
  pkg/kubefedctl/orphaning/disable.go
  pkg/kubefedctl/orphaning/enable.go
  pkg/kubefedctl/orphaning/orphaning.go
  pkg/kubefedctl/orphaning/status.go
  pkg/kubefedctl/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1050 Update repo for v0.1.0-rc4 release
  CHANGELOG.md
  charts/index.yaml
Labels: approved, cncf-cla: yes, size/S

#1048 Fix typo in the usage message of controller manager
  cmd/controller-manager/app/controller-manager.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1051 Update release script and doc
  docs/releasing.md
  scripts/build-release-artifacts.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1034 Adding documentation to solve the kubefed-admission-webhook timeout
  docs/environments/gke.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1053 Rename API group from kubefed.k8s.io to kubefed.io
  CHANGELOG.md
  PROJECT
  charts/kubefed/README.md
  charts/kubefed/charts/controllermanager/templates/clusterrole.yaml
  charts/kubefed/charts/controllermanager/templates/crds.yaml
  charts/kubefed/charts/controllermanager/templates/kubefedconfig.yaml
  charts/kubefed/charts/controllermanager/templates/rolebindings.yaml
  charts/kubefed/charts/controllermanager/templates/roles.yaml
  charts/kubefed/charts/controllermanager/templates/webhook.yaml
  charts/kubefed/templates/crds.yaml
  charts/kubefed/templates/federatedtypeconfig.yaml
  config/enabletypedirectives/clusterroles.rbac.authorization.k8s.io.yaml
  config/enabletypedirectives/configmaps.yaml
  config/enabletypedirectives/deployments.apps.yaml
  config/enabletypedirectives/ingresses.extensions.yaml
  config/enabletypedirectives/jobs.batch.yaml
  config/enabletypedirectives/namespaces.yaml
  config/enabletypedirectives/replicasets.apps.yaml
  config/enabletypedirectives/secrets.yaml
  config/enabletypedirectives/serviceaccounts.yaml
  config/enabletypedirectives/services.yaml
  config/kubefedconfig.yaml
  docs/development.md
  docs/ingress-service-dns-with-coredns.md
  docs/ingressdns-with-externaldns.md
  docs/servicedns-with-externaldns.md
  docs/userguide.md
  example/config/kubefedconfig.yaml
  example/sample1/federatedclusterrole.yaml
  example/sample1/federatedclusterrolebinding.yaml
  example/sample1/federatedconfigmap.yaml
  example/sample1/federateddeployment.yaml
  example/sample1/federatedingress.yaml
  example/sample1/federatedjob.yaml
  example/sample1/federatednamespace.yaml
  example/sample1/federatedsecret.yaml
  example/sample1/federatedservice.yaml
  example/sample1/federatedserviceaccount.yaml
  example/scheduling/federateddeployment-rsp.yaml
  pkg/apis/core/v1alpha1/doc.go
  pkg/apis/core/v1alpha1/register.go
  pkg/apis/core/v1beta1/doc.go
  pkg/apis/core/v1beta1/register.go
  pkg/apis/multiclusterdns/v1alpha1/doc.go
  pkg/apis/multiclusterdns/v1alpha1/register.go
  pkg/apis/scheduling/v1alpha1/doc.go
  pkg/apis/scheduling/v1alpha1/register.go
  pkg/controller/federatedtypeconfig/controller.go
  pkg/controller/sync/controller.go
  pkg/controller/util/managedlabel.go
  pkg/controller/util/orphaninganotation.go
  pkg/kubefedctl/enable/enable.go
  pkg/kubefedctl/federate/federate.go
  pkg/kubefedctl/options/options.go
  pkg/kubefedctl/orphaning/disable.go
  pkg/kubefedctl/orphaning/enable.go
  pkg/kubefedctl/orphaning/status.go
  scripts/delete-kubefed.sh
  scripts/sync-up-helm-chart.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#953 Report NamespaceNotFederated in propagation status
  CHANGELOG.md
  docs/userguide.md
  pkg/controller/sync/controller.go
  pkg/controller/sync/resource.go
  pkg/controller/sync/status/status.go
  scripts/pre-commit.sh
  test/common/crudtester.go
  test/e2e/crud.go
  test/e2e/framework/test_context.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1054 It should be `kubefedctl enable` to enable a federated type.
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1055 Rename PULL_REQUEST_TEMP.md -> PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1049 Update KubeFedCluster API optional fields
  charts/kubefed/charts/controllermanager/templates/crds.yaml
  pkg/apis/core/v1beta1/kubefedcluster_types.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/controller/kubefedcluster/clusterclient.go
  pkg/controller/kubefedcluster/controller.go
  pkg/controller/kubefedcluster/controller_test.go
  pkg/controller/servicedns/controller.go
  test/common/validation.go
  test/e2e/servicedns.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1030 Kubefedcluster: support ignore tls
  charts/kubefed/charts/controllermanager/templates/crds.yaml
  pkg/apis/core/v1beta1/kubefedcluster_types.go
  pkg/apis/core/v1beta1/validation/validation.go
  pkg/apis/core/v1beta1/validation/validation_test.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/controller/util/cluster_util.go
  pkg/kubefedctl/join.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1052 Support varying the apiVersion of target resources
  CHANGELOG.md
  pkg/client/generic/genericclient.go
  pkg/controller/sync/controller.go
  pkg/controller/sync/dispatch/checkunmanaged.go
  pkg/controller/sync/dispatch/managed.go
  pkg/controller/sync/dispatch/operation.go
  pkg/controller/sync/dispatch/unmanaged.go
  pkg/controller/sync/resource.go
  pkg/controller/util/federated_informer.go
  pkg/controller/util/overrides.go
  pkg/controller/util/podanalyzer/pod_helper.go
  pkg/controller/util/podanalyzer/pod_helper_test.go
  pkg/schedulingtypes/replicascheduler.go
  scripts/download-binaries.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#987 when ftc target version changed, sync controller should be refreshed
  pkg/controller/federatedtypeconfig/controller.go
  test/e2e/ftccontroller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1042 event for kubefedcluster
  pkg/controller/kubefedcluster/clusterclient.go
  pkg/controller/kubefedcluster/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1060 Extend race detection timeout to 900s from default 600s
  scripts/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1040 Generalize validation e2e tests for each validating resource type
  test/e2e/validation.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1059 Improve kubefedctl error message when KubeFedConfig not found
  pkg/kubefedctl/options/options.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1047 Cleanup generic status handling
  pkg/controller/sync/status/status.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1057 Update to use Kind v0.4.0 and remove a todo
  scripts/create-clusters.sh
  scripts/download-e2e-binaries.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1062 Make KubeFedConfig scope immutable
  CHANGELOG.md
  cmd/controller-manager/app/controller-manager.go
  pkg/apis/core/v1beta1/validation/validation.go
  pkg/apis/core/v1beta1/validation/validation_test.go
  pkg/controller/webhook/federatedtypeconfig/webhook.go
  pkg/controller/webhook/kubefedcluster/webhook.go
  pkg/controller/webhook/kubefedconfig/webhook.go
  pkg/controller/webhook/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1063 Add Error Event for FederatedNamespace
  pkg/controller/sync/accessor.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1065 Get curretContext when host-cluster-context is empty
  pkg/kubefedctl/join.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1056 check if federated type is referred by an existing FTC
  pkg/kubefedctl/enable/enable.go
Labels: approved, cncf-cla: yes, lgtm, size/S
