Repository kubernetes-sigs/kubefed, pull requests merged in 2019-06, with the labels that each got.

#706 Make installation compatible with macos under docker 18 with kind.
  docs/userguide.md
  scripts/create-clusters.sh
  scripts/fix-joined-kind-clusters.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#957 fix walkthrough failed in CI
  scripts/deploy-federated-nginx.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#958 Update golang build image to 1.12.5 to match .travis.yml
  .travis.yml
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#960 Gate Check for Klog package
  hack/verify-klog.sh
  scripts/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#959 Fix macos deployment compatibility
  docs/environments/kind.md
  docs/userguide.md
  scripts/create-clusters.sh
  scripts/download-binaries.sh
  scripts/fix-joined-kind-clusters.sh
  scripts/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#968 Update IngressDNS user guide with a clarification
  docs/ingressdns-with-externaldns.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#956 Separated Cluster Registration into a new .md file
  docs/cluster-registration.md
  docs/releasing.md
  docs/userguide.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/L

#972 Fixed minor comments for cluster registration doc
  docs/cluster-registration.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#966 Update KubeFedConfig API fields to be optional
  charts/kubefed/charts/controllermanager/templates/crds.yaml
  cmd/controller-manager/app/controller-manager.go
  pkg/apis/core/v1beta1/kubefedconfig_types.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#941 Webhook checking for KubeFedConfig
  CHANGELOG.md
  charts/kubefed/charts/controllermanager/templates/clusterrole.yaml
  charts/kubefed/charts/controllermanager/templates/clusterrolebindings.yaml
  charts/kubefed/charts/controllermanager/templates/rolebindings.yaml
  charts/kubefed/charts/controllermanager/templates/roles.yaml
  charts/kubefed/charts/controllermanager/templates/webhook.yaml
  cmd/controller-manager/app/controller-manager.go
  config/kubefedconfig.yaml
  pkg/apis/core/v1beta1/validation/validation.go
  pkg/apis/core/v1beta1/validation/validation_test.go
  pkg/controller/webhook/kubefedconfig/webhook.go
  pkg/features/features.go
  pkg/webhook/webhook.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#973 Fix lint errors introduced by #966 and #941 merging without rebase
  pkg/apis/core/v1beta1/validation/validation.go
  pkg/apis/core/v1beta1/validation/validation_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#974 Add admission webhook support for namespace-scoped deployments
  CHANGELOG.md
  charts/kubefed/README.md
  charts/kubefed/charts/controllermanager/templates/clusterrole.yaml
  charts/kubefed/charts/controllermanager/templates/clusterrolebindings.yaml
  charts/kubefed/charts/controllermanager/templates/rolebindings.yaml
  charts/kubefed/charts/controllermanager/templates/roles.yaml
  charts/kubefed/charts/controllermanager/templates/webhook.yaml
  scripts/deploy-kubefed.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#976 Fix KubeFedConfig validation of pointer fields
  pkg/apis/core/v1beta1/validation/validation.go
  pkg/apis/core/v1beta1/validation/validation_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#979 Update KubeFedConfig API time fields
  charts/kubefed/README.md
  charts/kubefed/charts/controllermanager/templates/crds.yaml
  charts/kubefed/charts/controllermanager/templates/kubefedconfig.yaml
  charts/kubefed/values.yaml
  cmd/controller-manager/app/controller-manager.go
  pkg/apis/core/v1beta1/kubefedconfig_types.go
  pkg/apis/core/v1beta1/validation/validation.go
  pkg/apis/core/v1beta1/validation/validation_test.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/controller/kubefedcluster/controller.go
  pkg/controller/kubefedcluster/controller_test.go
  pkg/controller/util/cluster_util.go
  pkg/controller/util/controllerconfig.go
  test/e2e/framework/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#985 Minor Cleanup in the scripts
  hack/go-tools/verify-gofmt.sh
  hack/update-gofmt.sh
  hack/verify-errpkg.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#978 Add mutating webhook support for KubeFedConfig
  charts/kubefed/charts/controllermanager/templates/clusterrole.yaml
  charts/kubefed/charts/controllermanager/templates/webhook.yaml
  pkg/controller/federatedtypeconfig/controller.go
  pkg/controller/webhook/kubefedconfig/webhook.go
  pkg/controller/webhook/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#994 Add explanation, how to configure PSP for the kubefed namespace on ICP
  docs/environments/icp.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#990 Fix disabling insecure registry in create clusters script
  scripts/create-clusters.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#989 Add Xun Pan as an approver
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#995 when DOCKER_PUSH= is set, the script should skip docker push
  scripts/deploy-kubefed.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#996 Fix typo in user-guide
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#992 Refactor and cleanup validation unit tests
  pkg/apis/core/v1beta1/validation/validation_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1005 Update static release badge to a dynamic one
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1007 configure images with a UID and set SC in deployments
  charts/kubefed/charts/controllermanager/templates/deployments.yaml
  images/kubefed/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#991 Replace override paths with JSON pointer style paths
  charts/kubefed/templates/crds.yaml
  example/sample1/federatedconfigmap.yaml
  example/sample1/federateddeployment.yaml
  example/sample1/federatedjob.yaml
  example/sample1/federatedsecret.yaml
  pkg/controller/sync/resource.go
  pkg/controller/util/overrides.go
  pkg/kubefedctl/enable/validation.go
  pkg/schedulingtypes/plugin.go
  scripts/deploy-federated-nginx.sh
  test/common/crudtester.go
  test/common/fixtures/configmaps.yaml
  test/common/fixtures/deployments.apps.yaml
  test/common/fixtures/jobs.batch.yaml
  test/common/fixtures/replicasets.apps.yaml
  test/common/fixtures/secrets.yaml
  test/e2e/crd.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1012 Ensure cluster scoped sync controller starts without namespace ftc
  pkg/controller/federatedtypeconfig/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1016 Update repo for v0.1.0-rc3 release
  CHANGELOG.md
  charts/index.yaml
Labels: approved, cncf-cla: yes, size/S

#993 Add FederatedTypeConfig e2e validation webhook test
  pkg/controller/webhook/federatedtypeconfig/webhook.go
  test/e2e/framework/framework.go
  test/e2e/framework/unmanaged.go
  test/e2e/validation.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1020 Update install instructions for kubefedctl
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/S
