Repository kubernetes-sigs/kubefed, pull requests merged in 2019-08, with the labels that each got.

#1072 fix-ca-for-k3s.sh: document that k3s v0.7.0 no longer needs this
  scripts/fix-ca-for-k3s.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1075 Update repo for release v0.1.0-rc5
  CHANGELOG.md
  charts/index.yaml
Labels: cncf-cla: yes, size/S

#1074 Update github pr template to reflect our use of CHANGELOG.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1070 Fix panic when statusCollectoin is enabled
  pkg/apis/core/v1beta1/federatedtypeconfig_types.go
  pkg/controller/status/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1041 Add KubeFedConfig validation e2e test
  pkg/apis/core/v1beta1/validation/validation_test.go
  test/common/validation.go
  test/e2e/validation.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1089 1087. Replica count of federated deployment is not updated by RSP plugin
  pkg/schedulingtypes/plugin.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1091 Add a shortname to federatedtypeconfig
  charts/kubefed/charts/controllermanager/templates/crds.yaml
  pkg/apis/core/v1beta1/federatedtypeconfig_types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1094 Add image build for darwin
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1095 Revert "Add image build for darwin"
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1068 Update CI to test against kube v1.15.0
  scripts/pre-commit.sh
  test/e2e/ftccontroller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1097 Fix logging statements: duration logging statement should be wrapped …
  pkg/controller/ingressdns/controller.go
  pkg/controller/schedulingpreference/controller.go
  pkg/controller/servicedns/controller.go
  pkg/controller/status/controller.go
  pkg/controller/sync/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1100 controller: process label updates to kubefedcluster resources
  pkg/controller/kubefedcluster/controller.go
  pkg/controller/util/federated_informer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1082 Require the spec field in generated federated types
  CHANGELOG.md
  charts/kubefed/templates/crds.yaml
  pkg/controller/sync/resource.go
  pkg/kubefedctl/enable/validation.go
  test/e2e/framework/framework.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1081 Add scripts to help automate KubeFed releases
  docs/releasing.md
  scripts/build-release-artifacts.sh
  scripts/build-release.sh
  scripts/create-gh-release.sh
  scripts/util.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1105 Issue #1104 Adding communication channel information to the README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1073 Remove inactive reviewers
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1086 Remove all metadata fields but labels from targets of kf federate
  CHANGELOG.md
  pkg/kubefedctl/federate/federate.go
  pkg/kubefedctl/federate/util.go
  test/e2e/federate.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1067 Add fatal check to deploy script for binary dependencies being installed
  scripts/deploy-kubefed.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1108 Fixing broken link in development.md
  docs/development.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1096 fix scheduler manager test case
  test/e2e/schedulermanager.go
  test/e2e/scheduling.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1076 kubefedctl: Set host cluster context to current context if empty
  CHANGELOG.md
  pkg/kubefedctl/join.go
  pkg/kubefedctl/options/options.go
  pkg/kubefedctl/orphaning/orphaning.go
  pkg/kubefedctl/unjoin.go
  pkg/kubefedctl/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1093 Refactor `kubefedctl join` to enable reuse for simulated scale testing
  pkg/kubefedctl/join.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1109 Fixing an unnecessary type conversion
  pkg/schedulingtypes/plugin.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1092 Add unit testing for pkg/schedulingtypes/updateOverridesMap
  CHANGELOG.md
  pkg/schedulingtypes/plugin_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1098 Skip writing propagated version to the API when unchanged
  CHANGELOG.md
  pkg/controller/sync/version/manager.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1115 Update repo for release v0.1.0-rc6
  CHANGELOG.md
  charts/index.yaml
Labels: approved, cncf-cla: yes, size/S

#1019 Adding e2e target for generating binaries for the e2e tests
  Makefile
  docs/development.md
  hack/go-tools/verify-gofmt.sh
  hack/verify-errpkg.sh
  scripts/download-binaries.sh
  scripts/pre-commit.sh
  scripts/update-bindata.sh
  test/common/bindata.go
  test/common/fixtures.go
  test/common/testobjects.go
  test/e2e/framework/enable.go
  test/e2e/leaderelection.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1103 kubefedctl federate: ensure that --dry-run avoids mutating api state
  pkg/kubefedctl/enable/enable.go
  pkg/kubefedctl/federate/federate.go
  test/e2e/crd.go
  test/e2e/ftccontroller.go
  test/e2e/schedulermanager.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1118 Fix BZ 1740052 - Federation of SAs and Secrets that have a : in them doesn't work because of CRD expression limitation
  pkg/kubefedctl/federate/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1113 The DEFAULT_KUBEFED_SCOPE env var was only being set the first time the KubeFedConfig didn't exist
  cmd/controller-manager/app/controller-manager.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1119 Add version info to KubeFed admission webhook
  pkg/webhook/webhook.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1121 Change shorthand --enable-type flag to avoid typo
  CHANGELOG.md
  pkg/kubefedctl/federate/federate.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1125 Update to use go 1.12.9
  .travis.yml
  Makefile
  pkg/apis/core/v1beta1/validation/validation_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1117 Update kubefed release automation scripts
  scripts/build-release.sh
  scripts/create-gh-release.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1120 controller/util: maintain a cache of cluster clients to reduce rest discovery
  pkg/controller/util/federated_informer.go
Labels: approved, cncf-cla: yes, lgtm, size/S
