Repository kubernetes-sigs/kubefed, pull requests merged in 2019-05, with the labels that each got.

#769 kubefed2 disable should delete the FTC rather than set propagationEnabled
  CHANGELOG.md
  pkg/kubefed2/disable.go
  pkg/kubefed2/enable/directive.go
  pkg/kubefed2/enable/enable.go
  pkg/kubefed2/join.go
  pkg/kubefed2/options/options.go
  pkg/kubefed2/unjoin.go
  test/e2e/crd.go
  test/e2e/scheduling.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#820 Cleanup ci script
  .travis.yml
  scripts/download-binaries.sh
  scripts/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#818 Update CI to test with Kubernetes 1.14.0
  scripts/create-clusters.sh
  scripts/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#822 LocalClusterReference updates
  charts/federation-v2/charts/controllermanager/templates/crds.yaml
  pkg/apis/core/v1alpha1/federatedcluster_types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#824 Add liveness probe to federation controller-manager
  charts/federation-v2/charts/controllermanager/templates/deployment.yaml
  cmd/controller-manager/app/controller-manager.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#831 Cleanup unused functions & packages
  pkg/controller/sharedinformers/doc.go
  pkg/controller/sharedinformers/informers.go
  pkg/controller/util/configmap.go
  pkg/controller/util/secret.go
  pkg/schedulingtypes/typeregistry.go
  test/common/dns.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#821 Fix issues with FederatedTypeConfig controller
  pkg/controller/federatedtypeconfig/controller.go
  pkg/controller/schedulingmanager/controller.go
  scripts/pre-commit.sh
  test/e2e/framework/controller.go
  test/e2e/scheduling.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#735 Refactor deletion handling
  pkg/controller/sync/accessor.go
  pkg/controller/sync/controller.go
  pkg/controller/sync/resource.go
  pkg/controller/util/deletionhelper/deletion_helper.go
  pkg/controller/util/federated_informer.go
  pkg/controller/util/federated_updater.go
  test/common/crudtester.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#803 Add leader election documentation to user guide
  charts/federation-v2/README.md
  charts/federation-v2/values.yaml
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#825 Rename references to kubefed2 with kubefedctl
  .golangci.yml
  CHANGELOG.md
  Makefile
  README.md
  cmd/hyperfed/main.go
  cmd/kubefedctl/main.go
  docs/concepts.md
  docs/releasing.md
  docs/userguide.md
  images/federation-v2/Dockerfile
  pkg/controller/sync/resource_test.go
  pkg/kubefedctl/disable.go
  pkg/kubefedctl/enable/directive.go
  pkg/kubefedctl/enable/enable.go
  pkg/kubefedctl/enable/schema.go
  pkg/kubefedctl/enable/util.go
  pkg/kubefedctl/enable/validation.go
  pkg/kubefedctl/federate/federate.go
  pkg/kubefedctl/federate/util.go
  pkg/kubefedctl/join.go
  pkg/kubefedctl/kubefedctl.go
  pkg/kubefedctl/options/options.go
  pkg/kubefedctl/unjoin.go
  pkg/kubefedctl/util/util.go
  pkg/kubefedctl/util/yaml_writer.go
  pkg/kubefedctl/version.go
  scripts/delete-federation.sh
  scripts/deploy-federation.sh
  scripts/fix-ca-for-k3s.sh
  scripts/pre-commit.sh
  scripts/sync-up-helm-chart.sh
  test/common/crudtester.go
  test/common/fixtures.go
  test/common/testobjects.go
  test/e2e/crd.go
  test/e2e/crud.go
  test/e2e/federate.go
  test/e2e/framework/enable.go
  test/e2e/scheduling.go
  test/e2e/version.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#823 Add a config option to control adopting pre-existing resources
  charts/federation-v2/README.md
  charts/federation-v2/charts/controllermanager/templates/federationconfig.yaml
  charts/federation-v2/values.yaml
  cmd/controller-manager/app/controller-manager.go
  pkg/apis/core/v1alpha1/federationconfig_types.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/sync/controller.go
  pkg/controller/sync/dispatch/managed.go
  pkg/controller/util/controllerconfig.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#817 Document how to configure helm rbac
  charts/federation-v2/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#830 Document how to determine that a target type is present in all federated clusters
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#807 FederatedCluster should use strongly-typed reference to 'Secret'
  charts/federation-v2/charts/controllermanager/templates/crds.yaml
  pkg/apis/core/v1alpha1/federatedcluster_types.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/kubefedctl/join.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#814 namespaced leader elector RBAC for cluster scope federation
  charts/federation-v2/charts/controllermanager/templates/clusterrole.yaml
  charts/federation-v2/charts/controllermanager/templates/role.yaml
  charts/federation-v2/charts/controllermanager/templates/rolebindings.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#724 Ensure managed label is removed from unmanaged resources
  CHANGELOG.md
  pkg/controller/sync/accessor.go
  pkg/controller/sync/controller.go
  test/common/crudtester.go
  test/e2e/crud.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#781 Don't fail without cluster scope.
  pkg/kubefedctl/join.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#819 Set default values for FederationConfig
  cmd/controller-manager/app/controller-manager.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#801 Removal of the FederatedTypeConfig for namespaces disables all namespaced sync controllers
  CHANGELOG.md
  pkg/apis/core/typeconfig/interface.go
  pkg/apis/core/v1alpha1/federatedtypeconfig_types.go
  pkg/controller/federatedtypeconfig/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#836 Increase log level of cluster status ok logs
  pkg/controller/util/federated_informer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#845 feat: remove init function in dnsendpoint common
  pkg/controller/dnsendpoint/common.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#741 Implement federate namespaces with content
  pkg/kubefedctl/enable/util.go
  pkg/kubefedctl/federate/federate.go
  pkg/kubefedctl/federate/util.go
  pkg/kubefedctl/util/yaml_writer.go
  test/e2e/federate.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#852 Update instructions for global.scope=Namespaced
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#853 Update repo for v0.0.10 release
  CHANGELOG.md
  charts/index.yaml
Labels: approved, cncf-cla: yes, size/S

#802 if FTC is not same version/group, reject request
  pkg/kubefedctl/enable/enable.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#849 Retry updating federated cluster status in servicedns e2e test
  test/e2e/servicedns.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#847 enable federation of types with federation group
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#848 doc installation for kubefedctl
  docs/development.md
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#791 Ensure finalizer is not removed if uncached managed resources exist
  pkg/controller/sync/controller.go
  pkg/controller/sync/dispatch/checkunmanaged.go
  pkg/controller/sync/dispatch/unmanaged.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#840 Small corrections in the document
  docs/development.md
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#844 Option to user to skip API Resources while federating ns with content
  pkg/kubefedctl/federate/federate.go
  pkg/kubefedctl/federate/util.go
  test/e2e/federate.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#861 Update changelog to reflact federate resource changes
  CHANGELOG.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#863 Add timeout to cluster clients used for cluster health checks
  pkg/controller/federatedcluster/clusterclient.go
  pkg/controller/federatedcluster/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#857 Switch from glog to klog
  Gopkg.lock
  cmd/controller-manager/app/controller-manager.go
  cmd/controller-manager/app/leaderelection/leaderelection.go
  cmd/controller-manager/app/options/options.go
  cmd/hyperfed/main.go
  pkg/client/generic/scheme/register.go
  pkg/controller/dnsendpoint/common.go
  pkg/controller/dnsendpoint/controller.go
  pkg/controller/federatedcluster/clusterclient.go
  pkg/controller/federatedcluster/controller.go
  pkg/controller/federatedtypeconfig/controller.go
  pkg/controller/ingressdns/controller.go
  pkg/controller/schedulingmanager/controller.go
  pkg/controller/schedulingpreference/controller.go
  pkg/controller/servicedns/controller.go
  pkg/controller/status/controller.go
  pkg/controller/sync/accessor.go
  pkg/controller/sync/controller.go
  pkg/controller/sync/dispatch/unmanaged.go
  pkg/controller/sync/resource_test.go
  pkg/controller/sync/version/manager.go
  pkg/controller/util/cluster_util.go
  pkg/controller/util/federated_informer.go
  pkg/controller/util/genericinformer.go
  pkg/controller/util/handlers_test.go
  pkg/controller/util/meta_test.go
  pkg/controller/util/planner/planner_test.go
  pkg/controller/util/podanalyzer/pod_helper_test.go
  pkg/features/features.go
  pkg/kubefedctl/disable.go
  pkg/kubefedctl/enable/enable.go
  pkg/kubefedctl/federate/federate.go
  pkg/kubefedctl/join.go
  pkg/kubefedctl/kubefedctl.go
  pkg/kubefedctl/options/options.go
  pkg/kubefedctl/unjoin.go
  pkg/kubefedctl/util/util.go
  pkg/kubefedctl/version.go
  pkg/schedulingtypes/interface.go
  pkg/schedulingtypes/plugin.go
  pkg/schedulingtypes/replicascheduler.go
  test/common/fixtures.go
  test/common/testobjects.go
  test/e2e/crd.go
  test/e2e/e2e.go
  test/e2e/e2e_test.go
  test/e2e/framework/framework.go
  test/e2e/framework/test_context.go
  test/e2e/framework/unmanaged.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#854 Add script to automate build of release artifacts
  charts/federation-v2/Chart.yaml
  docs/releasing.md
  scripts/build-release-artifacts.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#866 Fix dangling glog to klog
  pkg/controller/sync/dispatch/checkunmanaged.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#766 Bug fix for issue #680
  .travis.yml
  Makefile
  scripts/imagebuild.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#873 Update Makefile to use TRAVIS_BRANCH env var
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#874 Rename the default system namespace to kube-federation-system
  CHANGELOG.md
  charts/federation-v2/README.md
  config/federationconfig.yaml
  docs/development.md
  docs/ingress-service-dns-with-coredns.md
  docs/servicedns-with-externaldns.md
  docs/userguide.md
  example/config/federationconfig.yaml
  pkg/controller/util/cluster_util.go
  scripts/delete-federation.sh
  scripts/deploy-federation.sh
  scripts/fix-ca-for-k3s.sh
  scripts/pre-commit.sh
  scripts/sync-up-helm-chart.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#832 Federate resources from input yaml
  CHANGELOG.md
  pkg/kubefedctl/federate/federate.go
  pkg/kubefedctl/federate/util.go
  test/e2e/federate.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#881 Add some relevant badges to README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#870 Switch cluster references in placement from strings to objects
  CHANGELOG.md
  charts/federation-v2/templates/crds.yaml
  docs/userguide.md
  example/sample1/federatedclusterrole.yaml
  example/sample1/federatedclusterrolebinding.yaml
  example/sample1/federatedconfigmap.yaml
  example/sample1/federateddeployment.yaml
  example/sample1/federatedingress.yaml
  example/sample1/federatedjob.yaml
  example/sample1/federatednamespace.yaml
  example/sample1/federatedsecret.yaml
  example/sample1/federatedservice.yaml
  example/sample1/federatedserviceaccount.yaml
  pkg/controller/sync/placement.go
  pkg/controller/sync/placement_test.go
  pkg/controller/util/constants.go
  pkg/controller/util/placement.go
  pkg/kubefedctl/enable/validation.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#876 Replace cluster registry with APIEndpoint field on FederatedCluster
  CHANGELOG.md
  Makefile
  charts/federation-v2/README.md
  charts/federation-v2/charts/clusterregistry/Chart.yaml
  charts/federation-v2/charts/clusterregistry/templates/_helpers.tpl
  charts/federation-v2/charts/clusterregistry/templates/crds.yaml
  charts/federation-v2/charts/controllermanager/templates/clusterrole.yaml
  charts/federation-v2/charts/controllermanager/templates/crds.yaml
  charts/federation-v2/charts/controllermanager/templates/federationconfig.yaml
  charts/federation-v2/charts/controllermanager/templates/role.yaml
  charts/federation-v2/requirements.yaml
  charts/federation-v2/values.yaml
  cmd/controller-manager/app/controller-manager.go
  docs/development.md
  docs/environments/gke.md
  docs/environments/icp.md
  docs/userguide.md
  example/config/federationconfig.yaml
  pkg/apis/core/v1alpha1/federatedcluster_types.go
  pkg/apis/core/v1alpha1/federationconfig_types.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/client/generic/scheme/register.go
  pkg/controller/federatedcluster/clusterclient.go
  pkg/controller/federatedcluster/controller.go
  pkg/controller/util/cluster_util.go
  pkg/controller/util/controllerconfig.go
  pkg/controller/util/federated_informer.go
  pkg/kubefedctl/join.go
  pkg/kubefedctl/options/options.go
  pkg/kubefedctl/unjoin.go
  pkg/kubefedctl/util/util.go
  scripts/delete-federation.sh
  scripts/deploy-federation.sh
  scripts/pre-commit.sh
  test/e2e/e2e.go
  test/e2e/framework/test_context.go
  test/e2e/framework/unmanaged.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#877 Make FederatedCluster.SecretRef mandatory
  CHANGELOG.md
  charts/federation-v2/charts/controllermanager/templates/crds.yaml
  pkg/apis/core/v1alpha1/federatedcluster_types.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/util/cluster_util.go
  pkg/kubefedctl/join.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#888 Fix retry logic while updating cluster status in e2e test
  test/e2e/servicedns.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#892 Add note about configuration of travis and use of quay robot account
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#893 Run E2E with travis in forked repos
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M

#898 Align FederatedServiceStatus API with K8s API conventions
  charts/kubefed/charts/controllermanager/templates/crds.yaml
  pkg/apis/core/v1alpha1/federatedservicestatus_types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#896 Align PropagatedVersion API with K8s API conventions
  charts/kubefed/charts/controllermanager/templates/crds.yaml
  pkg/apis/core/v1alpha1/propagatedversion_types.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#897 Align ClusterPropagatedVersion API with K8s API conventions
  charts/kubefed/charts/controllermanager/templates/crds.yaml
  pkg/apis/core/v1alpha1/clusterpropagatedversion_types.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#886 Store ca bundle in FederatedCluster instead of the cluster secret
  CHANGELOG.md
  charts/kubefed/charts/controllermanager/templates/crds.yaml
  pkg/apis/core/v1alpha1/kubefedcluster_types.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/util/cluster_util.go
  pkg/kubefedctl/join.go
  scripts/fix-ca-for-k3s.sh
  scripts/sync-up-helm-chart.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#895 Document feature gates
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#859 idempotent unjoin
  pkg/kubefedctl/unjoin.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#902 Update golang to 1.12.5 (latest stable version)
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#885 Align FederatedTypeConfig API with K8s API conventions
  charts/kubefed/charts/controllermanager/templates/crds.yaml
  charts/kubefed/templates/federatedtypeconfig.yaml
  config/enabletypedirectives/services.yaml
  docs/userguide.md
  pkg/apis/core/common/constants.go
  pkg/apis/core/typeconfig/interface.go
  pkg/apis/core/typeconfig/util.go
  pkg/apis/core/v1alpha1/federatedtypeconfig_types.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/federatedtypeconfig/controller.go
  pkg/controller/schedulingmanager/controller.go
  pkg/controller/status/controller.go
  pkg/controller/sync/accessor.go
  pkg/controller/sync/controller.go
  pkg/controller/sync/resource.go
  pkg/kubefedctl/disable.go
  pkg/kubefedctl/enable/enable.go
  pkg/kubefedctl/enable/util.go
  pkg/kubefedctl/federate/federate.go
  pkg/schedulingtypes/plugin.go
  test/common/crudtester.go
  test/common/testobjects.go
  test/e2e/crd.go
  test/e2e/crud.go
  test/e2e/federate.go
  test/e2e/framework/controller.go
  test/e2e/framework/unmanaged.go
  test/e2e/placement.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#901 Doc immutable limitation
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#730 Documentation changes for issue #728
  docs/development.md
  docs/installation.md
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#904 Changes to naming from Federation to Kubefed
  docs/development.md
  docs/installation.md
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#887 Align FederationConfig API with K8s API conventions
  charts/kubefed/README.md
  charts/kubefed/charts/controllermanager/templates/crds.yaml
  charts/kubefed/charts/controllermanager/templates/kubefedconfig.yaml
  charts/kubefed/values.yaml
  cmd/controller-manager/app/controller-manager.go
  cmd/controller-manager/app/leaderelection/leaderelection.go
  cmd/controller-manager/app/options/options.go
  config/kubefedconfig.yaml
  docs/userguide.md
  example/config/kubefedconfig.yaml
  pkg/apis/core/v1alpha1/kubefedconfig_types.go
  pkg/controller/kubefedcluster/controller.go
  pkg/controller/kubefedcluster/controller_test.go
  pkg/controller/util/cluster_util.go
  pkg/controller/util/controllerconfig.go
  test/e2e/framework/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#910 Missed federation -> kubefed renames
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#911 Fix fix-ca-for-k3s.sh script
  scripts/fix-ca-for-k3s.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#913 Bugfix for run kubefed e2e test
  docs/development.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#903 Update docs of charts, minikube, and userguide
  charts/index.yaml
  charts/kubefed/README.md
  docs/development.md
  docs/environments/gke.md
  docs/environments/icp.md
  docs/environments/minikube.md
  docs/installation.md
  docs/userguide.md
  example/sample1/federatedclusterrole.yaml
  example/sample1/federatedclusterrolebinding.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#882 script for e2e use case of a simple nginx application
  example/sample1/configmap.yaml
  example/sample1/deployment.yaml
  example/sample1/service.yaml
  scripts/deploy-federated-nginx.sh
  scripts/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#920 update example of kubefedconfig.yaml use correct feature gates
  example/config/kubefedconfig.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#922 Update CHANGELOG with core kubefed API changes
  CHANGELOG.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#912 Rename Federation V2 to KubeFed in all docs
  CONTRIBUTING.md
  README.md
  charts/kubefed/README.md
  docs/concepts.md
  docs/development.md
  docs/environments/gke.md
  docs/environments/icp.md
  docs/environments/kind.md
  docs/environments/minikube.md
  docs/ingress-service-dns-with-coredns.md
  docs/ingressdns-with-externaldns.md
  docs/releasing.md
  docs/servicedns-with-externaldns.md
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#915 Align KubefedCluster API with K8s API conventions
  charts/kubefed/charts/controllermanager/templates/crds.yaml
  pkg/apis/core/v1beta1/kubefedcluster_types.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#906 Rewrite README intro
  CONTRIBUTING.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#923 s/Kubefed/KubeFed/ in the code
  charts/kubefed/Chart.yaml
  charts/kubefed/charts/controllermanager/Chart.yaml
  charts/kubefed/charts/controllermanager/templates/crds.yaml
  charts/kubefed/charts/controllermanager/templates/kubefedconfig.yaml
  cmd/controller-manager/app/controller-manager.go
  cmd/controller-manager/app/leaderelection/leaderelection.go
  cmd/controller-manager/app/options/options.go
  config/kubefedconfig.yaml
  example/config/kubefedconfig.yaml
  pkg/apis/core/v1beta1/kubefedcluster_types.go
  pkg/apis/core/v1beta1/kubefedconfig_types.go
  pkg/apis/core/v1beta1/validation/validation.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/controller/federatedtypeconfig/controller.go
  pkg/controller/ingressdns/controller.go
  pkg/controller/kubefedcluster/clusterclient.go
  pkg/controller/kubefedcluster/controller.go
  pkg/controller/kubefedcluster/controller_test.go
  pkg/controller/schedulingmanager/controller.go
  pkg/controller/schedulingpreference/controller.go
  pkg/controller/servicedns/controller.go
  pkg/controller/status/controller.go
  pkg/controller/sync/accessor.go
  pkg/controller/sync/controller.go
  pkg/controller/sync/placement.go
  pkg/controller/sync/placement_test.go
  pkg/controller/sync/resource.go
  pkg/controller/util/cluster_util.go
  pkg/controller/util/controllerconfig.go
  pkg/controller/util/federated_informer.go
  pkg/controller/webhook/kubefedcluster_webhook.go
  pkg/kubefedctl/disable.go
  pkg/kubefedctl/enable/enable.go
  pkg/kubefedctl/federate/federate.go
  pkg/kubefedctl/join.go
  pkg/kubefedctl/options/options.go
  pkg/kubefedctl/unjoin.go
  pkg/webhook/webhook.go
  test/e2e/crd.go
  test/e2e/crud.go
  test/e2e/federate.go
  test/e2e/framework/cluster.go
  test/e2e/framework/framework.go
  test/e2e/framework/test_context.go
  test/e2e/framework/unmanaged.go
  test/e2e/placement.go
  test/e2e/scheduling.go
  test/e2e/servicedns.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#925 Rename user-visible federation to 'federated' or 'kubefed'
  cmd/controller-manager/app/controller-manager.go
  cmd/controller-manager/app/leaderelection/leaderelection.go
  pkg/kubefedctl/disable.go
  pkg/kubefedctl/enable/directive.go
  pkg/kubefedctl/enable/enable.go
  pkg/kubefedctl/federate/federate.go
  pkg/kubefedctl/federate/util.go
  pkg/kubefedctl/join.go
  pkg/kubefedctl/options/options.go
  pkg/kubefedctl/unjoin.go
  test/e2e/crd.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#926 Update repo for v0.1.0-rc1 release
  CHANGELOG.md
  charts/index.yaml
Labels: approved, cncf-cla: yes, size/S

#927 Fix broken chart index link for v0.1.0-rc1
  charts/index.yaml
  charts/kubefed/README.md
  scripts/build-release-artifacts.sh
Labels: approved, cncf-cla: yes, size/XS

#890 Kubfedctl federate resource documentation
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#924 Update userguide for disabling federation of an API type
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#921 Minor updates to naming in userguide, fixes for headings and formatting
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#930 Update helm to 2.14
  scripts/download-binaries.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#934 Fixing broken link
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#940 Add release image verification steps
  docs/releasing.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#939 Cleanup docs to reflect kubefed rename
  docs/development.md
  docs/environments/gke.md
  docs/installation.md
  docs/servicedns-with-externaldns.md
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#937 Cleanup misc to reflect kubefed rename
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/failing-test.md
  .github/ISSUE_TEMPLATE/support.md
  .gitignore
  charts/kubefed/charts/controllermanager/templates/crds.yaml
  charts/kubefed/charts/controllermanager/templates/roles.yaml
  charts/kubefed/values.yaml
  docs/userguide.md
  pkg/apis/core/v1alpha1/propagatedversion_types.go
  pkg/apis/core/v1beta1/kubefedcluster_types.go
  pkg/apis/core/v1beta1/kubefedconfig_types.go
  pkg/apis/multiclusterdns/v1alpha1/domain_types.go
  pkg/apis/multiclusterdns/v1alpha1/servicednsrecord_types.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#933 Remove all trace of comparisonfield
  pkg/apis/core/common/constants.go
  pkg/apis/core/v1alpha1/clusterpropagatedversion_types.go
  pkg/apis/core/v1alpha1/propagatedversion_types.go
  pkg/kubefedctl/enable/directive.go
  test/e2e/crd.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#938 Cleanup code to reflect kubefed rename
  cmd/controller-manager/app/controller-manager.go
  cmd/controller-manager/app/options/options.go
  cmd/hyperfed/main.go
  pkg/apis/core/typeconfig/util.go
  pkg/apis/core/v1beta1/federatedtypeconfig_types.go
  pkg/controller/federatedtypeconfig/controller.go
  pkg/controller/ingressdns/controller.go
  pkg/controller/schedulingpreference/controller.go
  pkg/controller/servicedns/controller.go
  pkg/controller/status/controller.go
  pkg/controller/sync/controller.go
  pkg/controller/sync/placement.go
  pkg/controller/sync/resource.go
  pkg/controller/util/controllerconfig.go
  pkg/controller/util/federated_informer.go
  pkg/controller/util/managedlabel.go
  pkg/controller/util/resourceinformer.go
  pkg/controller/util/worker.go
  pkg/features/features.go
  pkg/kubefedctl/enable/enable.go
  pkg/kubefedctl/join.go
  pkg/kubefedctl/options/options.go
  pkg/kubefedctl/unjoin.go
  pkg/schedulingtypes/interface.go
  pkg/schedulingtypes/plugin.go
  pkg/schedulingtypes/replicascheduler.go
  test/common/crudtester.go
  test/common/dns.go
  test/e2e/framework/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#942 Fix crd doc formatting
  charts/kubefed/charts/controllermanager/templates/crds.yaml
  pkg/apis/core/v1beta1/kubefedconfig_types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#943 Retry adding cluster client if one doesn't exist during cluster healthcheck
  pkg/controller/kubefedcluster/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#945 adding non-root user to dockerfile
  charts/kubefed/charts/controllermanager/templates/deployments.yaml
  images/kubefed/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#949 Update the controller manager deployment to use more specific labels
  charts/kubefed/charts/controllermanager/templates/deployments.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#947 Cleanup tests to reflect kubefed rename
  test/common/crudtester.go
  test/e2e/crd.go
  test/e2e/crud.go
  test/e2e/e2e.go
  test/e2e/federate.go
  test/e2e/framework/controller.go
  test/e2e/framework/framework.go
  test/e2e/framework/test_context.go
  test/e2e/framework/unmanaged.go
  test/e2e/ingressdns.go
  test/e2e/leaderelection.go
  test/e2e/placement.go
  test/e2e/scheduling.go
  test/e2e/servicedns.go
  test/e2e/version.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#914 Validation for FederatedTypeConfig API
  CHANGELOG.md
  charts/kubefed/charts/controllermanager/templates/webhook.yaml
  pkg/apis/core/typeconfig/util.go
  pkg/apis/core/v1beta1/validation/validation.go
  pkg/apis/core/v1beta1/validation/validation_test.go
  pkg/controller/federatedtypeconfig/controller.go
  pkg/controller/schedulingmanager/controller.go
  pkg/controller/webhook/federatedtypeconfig/webhook.go
  pkg/controller/webhook/util.go
  pkg/kubefedctl/enable/enable.go
  pkg/kubefedctl/enable/util.go
  pkg/webhook/webhook.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#946 Cleanup scripts to reflect kubefed rename
  Makefile
  docs/development.md
  docs/userguide.md
  scripts/check-directive-fixtures.sh
  scripts/delete-kubefed.sh
  scripts/deploy-federated-nginx.sh
  scripts/deploy-kubefed-latest.sh
  scripts/deploy-kubefed.sh
  scripts/download-binaries.sh
  scripts/download-e2e-binaries.sh
  scripts/pre-commit.sh
  scripts/sync-up-helm-chart.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#948 More misc cleanup to reflect kubefed rename
  charts/kubefed/README.md
  charts/kubefed/charts/controllermanager/templates/clusterrole.yaml
  cmd/controller-manager/app/controller-manager.go
  cmd/controller-manager/app/leaderelection/leaderelection.go
  cmd/kubefedctl/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S
