Repository kubernetes-sigs/kubefed, pull requests merged in 2020-09, with the labels that each got.

#1279 Add a shortname to replicaschedulingpreference
  charts/kubefed/charts/controllermanager/crds/crds.yaml
  pkg/apis/scheduling/v1alpha1/replicaschedulingpreference_types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1280 chore: Add quickstart guide
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1282 chore: webhook functions now return AdmissionResponse
  pkg/controller/webhook/federatedtypeconfig/webhook.go
  pkg/controller/webhook/kubefedcluster/webhook.go
  pkg/controller/webhook/kubefedconfig/webhook.go
  pkg/controller/webhook/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1286 docs[userguide]: clean up redundant text
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1288 chart: cert-manager resources, allow these apiVersions be configurable
  charts/kubefed/charts/controllermanager/templates/webhook.yaml
  charts/kubefed/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
