Repository kubernetes-sigs/kubefed, pull requests merged in 2020-02, with the labels that each got.

#1186 Add jimmidyson to OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1192 feat: Add pprof profiling support
  cmd/controller-manager/app/controller-manager.go
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1193 chore: serve controller default metrics
  charts/kubefed/charts/controllermanager/templates/deployments.yaml
  charts/kubefed/charts/controllermanager/templates/service.yaml
  cmd/controller-manager/app/controller-manager.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#1195 (Updated) #1083: use unstructured runtime.Object for more detailed reflector logging
  pkg/controller/status/controller.go
  pkg/controller/sync/accessor.go
  pkg/controller/util/federated_informer.go
  pkg/controller/util/resourceinformer.go
  pkg/schedulingtypes/plugin.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1198 Release script improvements
  docs/releasing.md
  scripts/build-release-artifacts.sh
  scripts/build-release.sh
  scripts/create-gh-release.sh
  scripts/util.sh
Labels: approved, cncf-cla: yes, lgtm, size/S
