Repository kubernetes-sigs/kubefed, pull requests merged in 2020-05, with the labels that each got.

#1221 chore: make cluster creation work with kind v0.7.0
  scripts/create-clusters.sh
  scripts/download-e2e-binaries.sh
  scripts/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1222 Update repo for release v0.3.0
  CHANGELOG.md
  charts/index.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1225 Fix event source namespace
  pkg/controller/sync/accessor.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1227 Revert "Fix event source namespace"
  pkg/controller/sync/accessor.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1229 correct steps in ingress and service with coredns document
  docs/ingress-service-dns-with-coredns.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1228 ingress-nginx master changed, so use nginx-0.32.0
  docs/ingress-service-dns-with-coredns.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1231 cleanup legacy context after delete cluster
  scripts/delete-clusters.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1232 docs: adding documentation to add an array element using overrides
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
