Repository kubernetes-sigs/kubefed, pull requests merged in 2020-10, with the labels that each got.

#1289 chore: use cert-mananager.io/v1 group/version
  charts/kubefed/charts/controllermanager/templates/webhook.yaml
  charts/kubefed/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1290 chore: remove deprecated chart from repo
  charts/index.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1291 Update repo for release v0.4.1
  CHANGELOG.md
  charts/index.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1293 Remove self from OWNERS
  OWNERS
  docs/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1299 fix issue #1285
  pkg/controller/servicedns/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1294 fix: prefer core resources when enabling a type
  docs/userguide.md
  pkg/kubefedctl/enable/util.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1298 chore: disable CrossClusterDiscovery feature by default
  README.md
  charts/kubefed/README.md
  charts/kubefed/charts/controllermanager/templates/kubefedconfig.yaml
  cmd/controller-manager/app/controller-manager.go
  pkg/features/features.go
  scripts/deploy-kubefed.sh
  test/e2e/e2e.go
  test/e2e/framework/unmanaged.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1303 chore: Use Kubernetes v1.19.1 and kind v0.9.0 for testing
  scripts/create-clusters.sh
  scripts/download-e2e-binaries.sh
  scripts/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1302 chore: set the tolerations and nodeSelector
  charts/kubefed/README.md
  charts/kubefed/charts/controllermanager/templates/deployments.yaml
  charts/kubefed/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1301 chore: upgrade kubernetes dependencies
  go.mod
  go.sum
  pkg/controller/util/overrides.go
  test/common/bindata.go
  test/common/fixtures/deployments.apps.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1306 chore: Remove need for insecure registry
  Makefile
  docs/environments/kind.md
  scripts/create-clusters.sh
  scripts/delete-clusters.sh
  scripts/deploy-kubefed.sh
  scripts/download-e2e-binaries.sh
  scripts/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1307 Fix up CRD generation
  charts/kubefed/charts/controllermanager/crds/crds.yaml
  scripts/sync-up-helm-chart.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1305 chore: disable FederatedIngress feat by default
  README.md
  charts/kubefed/README.md
  charts/kubefed/charts/controllermanager/templates/kubefedconfig.yaml
  cmd/controller-manager/app/controller-manager.go
  pkg/features/features.go
  scripts/deploy-kubefed.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1308 Upgrade tools
  .travis.yml
  Makefile
  charts/kubefed/charts/controllermanager/crds/crds.yaml
  cmd/controller-manager/main.go
  cmd/hyperfed/main.go
  cmd/kubefedctl/main.go
  cmd/webhook/main.go
  pkg/apis/scheduling/v1alpha1/replicaschedulingpreference_types.go
  pkg/controller/dnsendpoint/controller.go
  pkg/controller/ingressdns/controller.go
  pkg/controller/schedulingmanager/controller.go
  pkg/controller/servicedns/controller.go
  pkg/controller/sync/dispatch/managed.go
  scripts/download-binaries.sh
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1309 fix: `make deploy.kind` didn't work, anymore.
  scripts/deploy-kubefed.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1310 chore: Add labels to service
  charts/kubefed/README.md
  charts/kubefed/charts/controllermanager/templates/service.yaml
  charts/kubefed/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1311 Update repo for release v0.5.0
  CHANGELOG.md
  charts/index.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M
