Repository kubernetes-sigs/kubefed, pull requests merged in 2020-08, with the labels that each got.

#1264 fix: pass correct values to Helm release in deploy script
  scripts/deploy-kubefed.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1263 feat: remove openshift/generic-admission-server
  charts/kubefed/charts/controllermanager/templates/deployments.yaml
  charts/kubefed/charts/controllermanager/templates/webhook.yaml
  cmd/hyperfed/main.go
  cmd/webhook/app/webhook.go
  cmd/webhook/main.go
  go.mod
  go.sum
  pkg/controller/webhook/federatedtypeconfig/webhook.go
  pkg/controller/webhook/kubefedcluster/webhook.go
  pkg/controller/webhook/kubefedconfig/webhook.go
  pkg/controller/webhook/util.go
  pkg/webhook/webhook.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1266 Improvements to deploy-kubefed.sh script
  Makefile
  docs/development.md
  scripts/deploy-kubefed.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1270 Dependency and golang version updates
  .travis.yml
  Makefile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#1237 docs: add kep about the status of the federated resources
  docs/keps/20200619-federated-resource-status.md
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1260 Helmv3 migration of the chart
  charts/kubefed/.gitignore
  charts/kubefed/Chart.yaml
  charts/kubefed/README.md
  charts/kubefed/charts/controllermanager/Chart.yaml
  charts/kubefed/charts/controllermanager/crds/crds.yaml
  charts/kubefed/crds/crds.yaml
  scripts/delete-kubefed.sh
  scripts/deploy-kubefed.sh
  scripts/download-binaries.sh
  scripts/sync-up-helm-chart.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1272 Helm chart tidy up
  Makefile
  charts/kubefed/Chart.yaml
  charts/kubefed/charts/controllermanager/templates/deployments.yaml
  charts/kubefed/requirements.yaml
  charts/kubefed/values.yaml
  scripts/deploy-kubefed.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1273 chart: enable cert-manager
  charts/kubefed/Chart.yaml
  charts/kubefed/charts/controllermanager/templates/deployments.yaml
  charts/kubefed/charts/controllermanager/templates/webhook.yaml
  charts/kubefed/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1275 Update repo for release v0.4.0
  CHANGELOG.md
  charts/index.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
