Repository kubernetes-sigs/kubefed, pull requests merged in 2020-03, with the labels that each got.

#1197 Update repo for release v0.2.0-alpha.1
  CHANGELOG.md
  charts/index.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1200 Bump Helm version to 2.16.3 in download-binaries script
  scripts/download-binaries.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1204 docs: add missing devel flag to helm commands (#1203)
  charts/kubefed/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1196 feat: add custom kubefed metrics
  cmd/controller-manager/app/controller-manager.go
  docs/keps/20200302-kubefed-metrics.md
  pkg/controller/federatedtypeconfig/controller.go
  pkg/controller/ingressdns/controller.go
  pkg/controller/kubefedcluster/clusterclient.go
  pkg/controller/kubefedcluster/controller.go
  pkg/controller/schedulingmanager/controller.go
  pkg/controller/schedulingpreference/controller.go
  pkg/controller/servicedns/controller.go
  pkg/controller/status/controller.go
  pkg/controller/sync/controller.go
  pkg/controller/sync/dispatch/managed.go
  pkg/controller/sync/dispatch/unmanaged.go
  pkg/controller/util/federated_informer.go
  pkg/kubefedctl/join.go
  pkg/kubefedctl/unjoin.go
  pkg/metrics/metrics.go
Labels: approved, cncf-cla: yes, lgtm, size/L
