Repository kubernetes-sigs/kubefed, pull requests merged in 2020-12, with the labels that each got.

#1323 make create-clusters.sh work based on kind document
  docs/environments/kind.md
  scripts/create-clusters.sh
  scripts/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1324 chore: improve some of the deployment and build scripts
  scripts/deploy-kubefed.sh
  scripts/sync-up-helm-chart.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1325 add helm parameter imagePullSecrets
  charts/kubefed/README.md
  charts/kubefed/charts/controllermanager/templates/deployments.yaml
  charts/kubefed/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1292 feat: collect remote resource status when enabled
  charts/kubefed/README.md
  charts/kubefed/charts/controllermanager/templates/kubefedconfig.yaml
  charts/kubefed/crds/crds.yaml
  charts/kubefed/values.yaml
  cmd/controller-manager/app/controller-manager.go
  config/kubefedconfig.yaml
  docs/development.md
  docs/keps/20200619-federated-resource-status.md
  example/config/kubefedconfig.yaml
  go.mod
  go.sum
  pkg/apis/core/v1beta1/federatedtypeconfig_types.go
  pkg/apis/core/v1beta1/validation/validation.go
  pkg/controller/federatedtypeconfig/controller.go
  pkg/controller/sync/controller.go
  pkg/controller/sync/dispatch/managed.go
  pkg/controller/sync/status/status.go
  pkg/controller/sync/status/status_test.go
  pkg/controller/util/controllerconfig.go
  pkg/features/features.go
  pkg/kubefedctl/enable/validation.go
  scripts/deploy-kubefed.sh
  test/common/bindata.go
  test/common/crudtester.go
  test/common/typeconfig.go
  test/e2e/crud.go
  test/e2e/defaulting.go
  test/e2e/framework/controller.go
  test/e2e/framework/unmanaged.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1328 optimize chart readme
  charts/kubefed/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1331 Update repo for release v0.6.0
  CHANGELOG.md
  charts/index.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M
