Repository kubernetes-sigs/kubefed, pull requests merged in 2020-04, with the labels that each got.

#1208 Add hectorj2f to OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1207 fix: enable command for crd resources
  docs/userguide.md
  pkg/kubefedctl/enable/schema.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#1199 FIX: namespaced condition for api resource
  pkg/kubefedctl/federate/federate.go
  pkg/kubefedctl/federate/federate_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1209 typo: changing 'federeate' for 'federate'
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1212 test: add test to validate the controller actions to keep the cluster data
  go.sum
  pkg/controller/kubefedcluster/controller.go
  pkg/controller/kubefedcluster/controller_integration_test.go
  pkg/controller/testdata/fixtures/crds.yaml
  scripts/download-binaries.sh
  scripts/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1216 Fix unit test failing with Go1.14+
  pkg/apis/core/v1beta1/validation/validation_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1218 Cleanup travis config about dep
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS
