Repository kubernetes-sigs/kubefed, pull requests merged in 2020-11, with the labels that each got.

#1315 fix: klog verbosity detection
  cmd/controller-manager/app/controller-manager.go
  cmd/hyperfed/main.go
  pkg/kubefedctl/kubefedctl.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1318 chore: make certain cert-manager properties configurable
  charts/kubefed/README.md
  charts/kubefed/charts/controllermanager/templates/webhook.yaml
  charts/kubefed/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1320 Update repo for release v0.5.1
  CHANGELOG.md
  charts/index.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1321 New reviewer: makkes
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1297 Transition CRDs from v1beta1 to v1
  CHANGELOG.md
  Makefile
  charts/kubefed/crds/crds.yaml
  cmd/controller-manager/app/controller-manager.go
  cmd/controller-manager/app/options/options.go
  go.mod
  go.sum
  pkg/apis/core/v1beta1/defaults/defaults_test.go
  pkg/apis/core/v1beta1/federatedtypeconfig_types.go
  pkg/apis/core/v1beta1/kubefedconfig_types.go
  pkg/apis/core/v1beta1/validation/validation.go
  pkg/apis/core/v1beta1/validation/validation_test.go
  pkg/controller/testdata/fixtures/crds.yaml
  pkg/kubefedctl/disable.go
  pkg/kubefedctl/enable/enable.go
  pkg/kubefedctl/enable/schema.go
  pkg/kubefedctl/enable/util.go
  pkg/kubefedctl/enable/validation.go
  pkg/kubefedctl/join.go
  pkg/kubefedctl/options/options.go
  scripts/sync-up-helm-chart.sh
  test/common/validation.go
  test/e2e/crd.go
  test/e2e/defaulting.go
  test/e2e/framework/cleanup.go
  test/e2e/ftccontroller.go
  test/e2e/scale.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL
