Repository kubernetes-sigs/kubefed, pull requests merged in 2020-07, with the labels that each got.

#1248 Fix service status not working issue
  pkg/controller/status/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1239 Correct docs for a Cluster Selector case
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1251 Update dependency to kubernetes 1.18.6
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#1245 Set default log level for kubefed controller manager.
  charts/kubefed/charts/controllermanager/templates/deployments.yaml
  charts/kubefed/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1256 Update repo for release v0.3.1
  CHANGELOG.md
  charts/index.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1238 docs: kep to propose a pull reconciliation model
  docs/keps/20200619-kubefed-pull-reconciliation.md
  docs/keps/images/kubefedArch.jpg
  docs/keps/images/kubefedv2Example.jpg
  docs/keps/images/kubefedv2_seconditeration.jpg
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#1261 charts: split properties for webhook and manager
  charts/kubefed/charts/controllermanager/templates/deployments.yaml
  charts/kubefed/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M
