Repository kubernetes-sigs/kubefed, pull requests merged in 2021-03, with the labels that each got.

#1367 Fix webhook cmd
  cmd/webhook/app/webhook.go
  cmd/webhook/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1361 kubefedcluster use cadata in kubeconfig file
  docs/cluster-registration.md
  pkg/kubefedctl/join.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1360 Remove FederatedIngress feature
  README.md
  charts/kubefed/README.md
  charts/kubefed/charts/controllermanager/crds/crds.yaml
  charts/kubefed/charts/controllermanager/templates/kubefedconfig.yaml
  charts/kubefed/charts/controllermanager/templates/post-install-job.yaml
  charts/kubefed/values.yaml
  cmd/controller-manager/app/controller-manager.go
  config/kubefedconfig.yaml
  docs/concepts.md
  docs/ingress-service-dns-with-coredns.md
  docs/ingressdns-with-externaldns.md
  docs/servicedns-with-externaldns.md
  docs/userguide.md
  example/config/kubefedconfig.yaml
  pkg/apis/addtoscheme_multiclusterdns_v1alpha1.go
  pkg/apis/core/v1beta1/validation/validation.go
  pkg/apis/multiclusterdns/group.go
  pkg/apis/multiclusterdns/v1alpha1/dnsendpoint_types.go
  pkg/apis/multiclusterdns/v1alpha1/domain_types.go
  pkg/apis/multiclusterdns/v1alpha1/groupversion_info.go
  pkg/apis/multiclusterdns/v1alpha1/ingressdnsrecord_types.go
  pkg/apis/multiclusterdns/v1alpha1/servicednsrecord_types.go
  pkg/apis/multiclusterdns/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/dnsendpoint/common.go
  pkg/controller/dnsendpoint/common_test.go
  pkg/controller/dnsendpoint/controller.go
  pkg/controller/dnsendpoint/ingress.go
  pkg/controller/dnsendpoint/ingress_test.go
  pkg/controller/dnsendpoint/service.go
  pkg/controller/dnsendpoint/service_test.go
  pkg/controller/ingressdns/controller.go
  pkg/features/features.go
  scripts/deploy-kubefed.sh
  scripts/pre-commit.sh
  test/common/bindata.go
  test/common/dns.go
  test/common/util.go
  test/e2e/framework/controller.go
  test/e2e/framework/unmanaged.go
  test/e2e/ingressdns.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1371 enable workqueue metrics for all controllers
  pkg/controller/federatedtypeconfig/controller.go
  pkg/controller/schedulingmanager/controller.go
  pkg/controller/schedulingpreference/controller.go
  pkg/controller/status/controller.go
  pkg/controller/sync/controller.go
  pkg/controller/util/worker.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1382 bugfix: register workqueue metrics in controller-runtime firstly
  cmd/controller-manager/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1377 feat: add a proxy url field to kubefed clusters
  charts/kubefed/charts/controllermanager/crds/crds.yaml
  go.mod
  pkg/apis/core/v1beta1/kubefedcluster_types.go
  pkg/apis/core/v1beta1/kubefedcluster_types_test.go
  pkg/apis/core/v1beta1/suite_test.go
  pkg/apis/core/v1beta1/validation/validation.go
  pkg/apis/core/v1beta1/validation/validation_test.go
  pkg/controller/util/cluster_util.go
  pkg/kubefedctl/join.go
  pkg/kubefedctl/join_test.go
  pkg/kubefedctl/suite_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#1385 Replica rebalance reconciliation fix
  pkg/controller/util/podanalyzer/pod_helper.go
  pkg/controller/util/podanalyzer/pod_helper_test.go
  pkg/schedulingtypes/replicascheduler.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1380 Infinite reconciliation loop (rawstatuscollection)
  pkg/controller/sync/controller.go
  pkg/controller/sync/status/status.go
  pkg/controller/sync/status/status_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1387 Update repo for release v0.7.0
  CHANGELOG.md
  charts/index.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1388 added blank import to ensure correct workqueue metric registration
  cmd/hyperfed/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
