Repository kubernetes-sigs/kubefed, pull requests merged in 2021-04, with the labels that each got.

#1379 make objects in workqueue "comparable" to avoid multiple reconciliations on one object at same time
  pkg/controller/util/worker.go
  pkg/controller/util/worker_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1399 correct command line example for test
  docs/development.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1332 Fix error on exiting
  pkg/controller/util/cluster_util.go
  pkg/kubefedctl/join.go
  test/e2e/scale.go
Labels: approved, cncf-cla: yes, lgtm, lifecycle/stale, size/L

#1389 use merge-patch on finalizer operations to resolve racing conflicts
  charts/kubefed/charts/controllermanager/templates/aggregate_clusterroles.yaml
  charts/kubefed/charts/controllermanager/templates/clusterrole.yaml
  charts/kubefed/charts/controllermanager/templates/roles.yaml
  pkg/client/generic/genericclient.go
  pkg/controller/federatedtypeconfig/controller.go
  pkg/controller/sync/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1383 cmd/controller-manager: optimize code
  cmd/controller-manager/app/controller-manager.go
Labels: approved, cncf-cla: yes, lgtm, size/M
