Repository kubernetes-sigs/kubefed, pull requests merged in 2021-02, with the labels that each got.

#1351 feature: remove CrossClusterDiscovery alpha feature
  README.md
  charts/kubefed/README.md
  charts/kubefed/charts/controllermanager/templates/kubefedconfig.yaml
  charts/kubefed/charts/controllermanager/templates/post-install-job.yaml
  charts/kubefed/values.yaml
  cmd/controller-manager/app/controller-manager.go
  config/kubefedconfig.yaml
  docs/ingress-service-dns-with-coredns.md
  docs/userguide.md
  example/config/kubefedconfig.yaml
  pkg/apis/core/v1beta1/validation/validation.go
  pkg/controller/kubefedcluster/controller.go
  pkg/controller/servicedns/controller.go
  pkg/features/features.go
  scripts/deploy-kubefed.sh
  scripts/pre-commit.sh
  test/common/bindata.go
  test/e2e/framework/controller.go
  test/e2e/framework/unmanaged.go
  test/e2e/servicedns.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1357 Upgrade dependencies
  charts/kubefed/charts/controllermanager/crds/crds.yaml
  cmd/controller-manager/app/controller-manager.go
  cmd/controller-manager/app/leaderelection/leaderelection.go
  cmd/hyperfed/main.go
  cmd/webhook/app/webhook.go
  go.mod
  go.sum
  pkg/controller/dnsendpoint/common.go
  pkg/controller/dnsendpoint/controller.go
  pkg/controller/federatedtypeconfig/controller.go
  pkg/controller/ingressdns/controller.go
  pkg/controller/kubefedcluster/clusterclient.go
  pkg/controller/kubefedcluster/controller.go
  pkg/controller/schedulingmanager/controller.go
  pkg/controller/schedulingpreference/controller.go
  pkg/controller/status/controller.go
  pkg/controller/sync/accessor.go
  pkg/controller/sync/controller.go
  pkg/controller/sync/dispatch/checkunmanaged.go
  pkg/controller/sync/dispatch/managed.go
  pkg/controller/sync/dispatch/unmanaged.go
  pkg/controller/sync/status/status.go
  pkg/controller/sync/version/manager.go
  pkg/controller/util/cluster_util.go
  pkg/controller/util/federated_informer.go
  pkg/controller/webhook/federatedtypeconfig/webhook.go
  pkg/controller/webhook/kubefedcluster/webhook.go
  pkg/controller/webhook/kubefedconfig/webhook.go
  pkg/features/features.go
  pkg/kubefedctl/disable.go
  pkg/kubefedctl/enable/enable.go
  pkg/kubefedctl/enable/util.go
  pkg/kubefedctl/federate/federate.go
  pkg/kubefedctl/federate/util.go
  pkg/kubefedctl/join.go
  pkg/kubefedctl/kubefedctl.go
  pkg/kubefedctl/orphaning/disable.go
  pkg/kubefedctl/orphaning/enable.go
  pkg/kubefedctl/orphaning/orphaning.go
  pkg/kubefedctl/orphaning/status.go
  pkg/kubefedctl/unjoin.go
  pkg/metrics/metrics.go
  pkg/schedulingtypes/plugin.go
  pkg/schedulingtypes/replicascheduler.go
  test/e2e/e2e.go
  test/e2e/framework/test_context.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1355 Feature: support DeleteOptions when deleting resources in member clusters
  pkg/client/generic/genericclient.go
  pkg/controller/sync/controller.go
  pkg/controller/sync/dispatch/managed.go
  pkg/controller/sync/dispatch/unmanaged.go
  pkg/controller/util/deletionannotation.go
  pkg/controller/util/deletionannotation_test.go
  test/common/crudtester.go
  test/e2e/deleteoptions.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L
