Repository kubernetes-sigs/kubefed, pull requests merged in 2021-05, with the labels that each got.

#1408 Add more error logs for sync controller & kubefedcluster controller
  pkg/controller/kubefedcluster/controller.go
  pkg/controller/sync/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1400 feat: make concurrency of the worker configurable
  .gitignore
  charts/kubefed/README.md
  charts/kubefed/charts/controllermanager/crds/crds.yaml
  charts/kubefed/charts/controllermanager/templates/kubefedconfig.yaml
  charts/kubefed/values.yaml
  cmd/controller-manager/app/controller-manager.go
  config/kubefedconfig.yaml
  pkg/apis/core/v1beta1/defaults/defaults.go
  pkg/apis/core/v1beta1/defaults/defaults_test.go
  pkg/apis/core/v1beta1/kubefedconfig_types.go
  pkg/apis/core/v1beta1/validation/validation.go
  pkg/apis/core/v1beta1/validation/validation_test.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/controller/federatedtypeconfig/controller.go
  pkg/controller/schedulingmanager/controller.go
  pkg/controller/schedulingpreference/controller.go
  pkg/controller/status/controller.go
  pkg/controller/sync/controller.go
  pkg/controller/testdata/fixtures/crds.yaml
  pkg/controller/util/controllerconfig.go
  pkg/controller/util/worker.go
  pkg/controller/util/worker_test.go
  test/common/bindata.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1410 fixed false api resource error log in kubefedctl
  pkg/kubefedctl/enable/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1409 feat:Use patch to replace update in generic client for multi cases
  pkg/controller/sync/dispatch/unmanaged.go
  pkg/kubefedctl/disable.go
  pkg/kubefedctl/enable/enable.go
  pkg/kubefedctl/join.go
  test/common/typeconfig.go
  test/e2e/crud.go
  test/e2e/validation.go
Labels: approved, cncf-cla: yes, lgtm, size/M
