Repository kubernetes-sigs/kubefed, pull requests merged in 2021-06, with the labels that each got.

#1420 build: Switch to Github Actions from Travis
  .github/workflows/build.yml
  .github/workflows/push.yml
  .travis.yml
  Makefile
  hack/verify-docfiles.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1422 build: Remove need for TTY when running in Github Actions
  .github/workflows/build.yml
  .github/workflows/push.yml
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#1423 Remove last vestiges of travis and fix release process for Github Actions
  .github/workflows/build-and-test.yml
  .github/workflows/test-and-push.yml
  Makefile
  README.md
  docs/releasing.md
  scripts/build-release.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1421 docs: update README.md to reflect current projectstate
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1393 add intersection behavior for RSP
  charts/kubefed/charts/controllermanager/crds/crds.yaml
  pkg/apis/scheduling/v1alpha1/replicaschedulingpreference_types.go
  pkg/controller/schedulingmanager/controller.go
  pkg/controller/sync/placement.go
  pkg/controller/sync/resource.go
  pkg/controller/util/placement.go
  pkg/controller/util/placement_test.go
  pkg/schedulingtypes/interface.go
  pkg/schedulingtypes/plugin.go
  pkg/schedulingtypes/replicascheduler.go
  test/e2e/schedulermanager.go
  test/e2e/scheduling.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1415 Update controller-runtime to v0.8.3
  cmd/webhook/main.go
  go.mod
  go.sum
  pkg/apis/core/v1beta1/kubefedcluster_types_test.go
  pkg/apis/core/v1beta1/suite_test.go
  pkg/client/generic/genericclient.go
  pkg/controller/federatedtypeconfig/controller.go
  pkg/controller/kubefedcluster/controller.go
  pkg/controller/kubefedcluster/controller_integration_test.go
  pkg/controller/schedulingpreference/controller.go
  pkg/controller/status/controller.go
  pkg/controller/sync/accessor.go
  pkg/controller/sync/controller.go
  pkg/controller/sync/dispatch/checkunmanaged.go
  pkg/controller/sync/dispatch/managed.go
  pkg/controller/sync/resource.go
  pkg/controller/sync/version/adapter.go
  pkg/controller/sync/version/cluster.go
  pkg/controller/sync/version/manager.go
  pkg/controller/sync/version/namespaced.go
  pkg/controller/util/cluster_util.go
  pkg/controller/util/federated_informer.go
  pkg/controller/util/finalizers/finalizers.go
  pkg/controller/util/finalizers/finalizers_test.go
  pkg/controller/util/genericinformer.go
  pkg/controller/util/handlers.go
  pkg/controller/util/handlers_test.go
  pkg/controller/util/meta.go
  pkg/controller/util/qualifiedname.go
  pkg/controller/util/resourceinformer.go
  pkg/controller/util/worker.go
  pkg/controller/webhook/federatedtypeconfig/webhook.go
  pkg/controller/webhook/kubefedcluster/webhook.go
  pkg/controller/webhook/kubefedconfig/webhook.go
  pkg/controller/webhook/util.go
  pkg/kubefedctl/enable/enable.go
  pkg/kubefedctl/suite_test.go
  pkg/schedulingtypes/interface.go
  pkg/schedulingtypes/replicascheduler.go
  pkg/schedulingtypes/resources.go
  test/common/util.go
  test/e2e/defaulting.go
  test/e2e/framework/wait.go
  test/e2e/validation.go
  test/e2e/version.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1425 Upgrade to controller-runtime 0.9.0
  go.mod
  go.sum
  test/e2e/validation.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1426 Upgrade golangci-lint and helm
  Makefile
  hack/verify-errpkg.sh
  pkg/controller/kubefedcluster/clusterclient.go
  pkg/kubefedctl/federate/util.go
  pkg/schedulingtypes/replicascheduler.go
  scripts/download-binaries.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1427 Kind and Kubernetes upgrade
  charts/kubefed/Chart.yaml
  charts/kubefed/charts/controllermanager/templates/webhook.yaml
  docs/development.md
  docs/environments/kind.md
  pkg/controller/sync/dispatch/retain.go
  pkg/controller/sync/dispatch/retain_test.go
  pkg/kubefedctl/federate/federate.go
  pkg/schedulingtypes/replicascheduler.go
  scripts/create-clusters.sh
  scripts/download-e2e-binaries.sh
  scripts/pre-commit.sh
  test/common/crudtester.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1429 Update repo for release
  CHANGELOG.md
  charts/index.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1430 build: Use gh instead of hub CLI for release automation
  scripts/build-release.sh
  scripts/create-gh-release.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1416 make restclient config configurable
  cmd/controller-manager/app/controller-manager.go
  scripts/pre-commit.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1428 fix: retry on recoverable propagation failure
  pkg/controller/sync/controller.go
  pkg/controller/sync/status/status.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1432 build(deps): Upgrade and align k8s.io dependency versions
  charts/kubefed/charts/controllermanager/crds/crds.yaml
  go.mod
  go.sum
  pkg/kubefedctl/enable/schema.go
  tools/go.mod
  tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1424 fix(postinstall-job): Allow postinstall job to choose a docker repo/image
  charts/kubefed/README.md
  charts/kubefed/charts/controllermanager/templates/post-install-job.yaml
  charts/kubefed/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1433 build: Properly add asset files to github release
  scripts/create-gh-release.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1435 fix: Support Kubernetes pre-release versions in kubefed chart
  charts/kubefed/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1436 Update repo for release v0.8.1
  CHANGELOG.md
  charts/index.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1437 build: Another fix to release script
  scripts/create-gh-release.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS
