Repository kubernetes-sigs/kubefed, pull requests merged in 2021-01, with the labels that each got.

#1347 retain healthCheckNodePort for service when updating
  pkg/controller/sync/dispatch/retain.go
  pkg/controller/sync/dispatch/retain_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1334 exec enable cmd ignore ignore some apiservices error
  pkg/kubefedctl/enable/util.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1346 fix: broken upgrade path from previous versions
  charts/kubefed/charts/controllermanager/templates/kubefedconfig.yaml
  charts/kubefed/charts/controllermanager/templates/post-install-job.yaml
  scripts/deploy-kubefed.sh
  scripts/pre-commit.sh
  scripts/util.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1349 Update repo for release v0.6.1
  CHANGELOG.md
  charts/index.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
