Repository kubernetes-sigs/kubefed, pull requests merged in 2022-08, with the labels that each got.

#1515 fix: Use specific service account token secret for join
  pkg/kubefedctl/join.go
  pkg/kubefedctl/util/util.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1517 fix: Wait for SA token to be populated
  pkg/kubefedctl/join.go
Labels: cncf-cla: yes, lgtm, approved, size/XS

#1518 build: Use KinD for syncing helm chart resources
  scripts/download-binaries.sh
  scripts/sync-up-helm-chart.sh
  scripts/util.sh
Labels: cncf-cla: yes, lgtm, approved, size/M

#1520 build: Ensure correct go-bindata is used
  scripts/update-bindata.sh
Labels: cncf-cla: yes, lgtm, approved, size/S

#1519 build: Use setup-envtest to download later version of envtest
  Makefile
  docs/development.md
  scripts/download-binaries.sh
Labels: cncf-cla: yes, lgtm, approved, size/M

#1521 fix: Move ingress from extensions/v1beta1 to networking.k8s.io/v1
  charts/kubefed/templates/federatedtypeconfig.yaml
  config/enabletypedirectives/ingresses.networking.k8s.io.yaml
  test/common/bindata.go
  test/common/fixtures/ingresses.extensions.yaml
  test/common/fixtures/ingresses.networking.k8s.io.yaml
Labels: cncf-cla: yes, lgtm, approved, size/M

#1455 fixes #1454: add document for intersectWithClusterSelector
  docs/userguide.md
Labels: cncf-cla: yes, lgtm, approved, size/S

#1516 build: Use k8s v1.24 for tests
  Makefile
  docs/environments/kind.md
  scripts/create-clusters.sh
  scripts/download-binaries.sh
  scripts/download-e2e-binaries.sh
  scripts/pre-commit.sh
Labels: cncf-cla: yes, lgtm, approved, size/S

#1522 Update repo for release v0.10.0
  CHANGELOG.md
  charts/index.yaml
Labels: cncf-cla: yes, lgtm, approved, size/M
